import React, { useCallback, useEffect, useSyncExternalStore } from "react";
import { createPortal } from "react-dom";
import { Toast, type Tone } from "./components";

type ToastRecord={id:string;title:string;message?:string;tone:Tone;duration:number};
let records:ToastRecord[]=[];const listeners=new Set<()=>void>();
const emit=()=>listeners.forEach(listener=>listener());
export function showBvToast(input:Omit<ToastRecord,"id">&{id?:string}){const id=input.id??`${input.title}:${input.message??""}`,existing=records.findIndex(item=>item.id===id),next={...input,id};records=existing>=0?[...records.slice(0,existing),next,...records.slice(existing+1)]:[...records,next].slice(-3);emit();return id}
export function dismissBvToast(id:string){records=records.filter(item=>item.id!==id);emit()}
const subscribe=(listener:()=>void)=>{listeners.add(listener);return()=>listeners.delete(listener)};
const snapshot=()=>records;

export function BvGlobalToastStack(){const items=useSyncExternalStore(subscribe,snapshot,snapshot),position=useCallback(()=>{const host=document.getElementById("bv-global-toast-stack");if(!host)return;const blockers=[...document.querySelectorAll<HTMLElement>(".comfyui-bottom-panel,.bottom-panel,.actionbar,[class*='bottom'][class*='toolbar'],#graph-canvas-container [role='toolbar'],#bv-ui-window-shelf")].filter(node=>node.offsetParent!==null).map(node=>node.getBoundingClientRect()).filter(box=>box.bottom>window.innerHeight-160);const bottom=Math.max(16,...blockers.map(box=>Math.max(0,window.innerHeight-box.top+8)));host.style.setProperty("--bv-toast-bottom",`${bottom}px`)},[]);useEffect(()=>{const show=(event:Event)=>{const detail=(event as CustomEvent<Partial<ToastRecord>>).detail;if(!detail?.title)return;showBvToast({title:detail.title,message:detail.message,tone:detail.tone??"neutral",duration:detail.duration??4500})};window.addEventListener("bv-show-toast",show);return()=>window.removeEventListener("bv-show-toast",show)},[]);useEffect(()=>{position();const observer=new ResizeObserver(position),mutation=new MutationObserver(position);document.querySelectorAll<HTMLElement>("body *").forEach(node=>{if(node.offsetParent!==null&&node.getBoundingClientRect().bottom>window.innerHeight-180)observer.observe(node)});mutation.observe(document.body,{childList:true,subtree:true});window.addEventListener("resize",position);return()=>{observer.disconnect();mutation.disconnect();window.removeEventListener("resize",position)}},[position]);if(!items.length)return null;return createPortal(<div id="bv-global-toast-stack" className="bv-ui bv-density-compact bv-toast-stack bv-global-toast-stack" aria-live="polite">{items.map(item=><Toast key={item.id} tone={item.tone} title={item.title} duration={item.duration} onClose={()=>dismissBvToast(item.id)}>{item.message}</Toast>)}</div>,document.body)}
