import React, { useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { Button, ToggleField } from "./components";
import { BV_WINDOW_VISIBILITY_CHANGED_EVENT } from "./windowRegistry";

export type ToolbarLauncherItem = { id:string; label:string; meta?:string; disabled?:boolean; hidden?:boolean; secondary?:{label:string;onSelect:()=>void}; onReveal?:()=>void; onSelect:()=>void };
export type ToolbarLauncherColumn = { id:string; label:string; items:ToolbarLauncherItem[] };
export const BV_TOOLBAR_LAUNCHER_TOGGLE_EVENT="bv-toggle-toolbar-window-launcher";

export function ToolbarWindowLauncher({getColumns}:{getColumns:(includeHidden:boolean)=>ToolbarLauncherColumn[]}) {
    const [position,setPosition]=useState({left:0,top:0});
    const [open,setOpen]=useState(false),[includeHidden,setIncludeHidden]=useState(false),[,setVisibilityRevision]=useState(0);
    const launcher=useRef<HTMLDivElement>(null),openTimer=useRef<number>(),closeTimer=useRef<number>(),suppressHideUntil=useRef(0);
    const clearTimers=()=>{if(openTimer.current)window.clearTimeout(openTimer.current);if(closeTimer.current)window.clearTimeout(closeTimer.current)};
    const positionLauncher=(anchor:HTMLElement,count:number)=>{const box=anchor.getBoundingClientRect(),width=Math.min(Math.max(1,count)*220,window.innerWidth-24),height=Math.min(420,window.innerHeight-84),left=Math.max(12,Math.min(box.left,window.innerWidth-width-12)),top=box.bottom+6+height<=window.innerHeight-12?box.bottom+6:Math.max(12,box.top-height-6);return{left,top}};
    const reveal=useCallback((delay:number,requestedAnchor?:HTMLElement)=>{clearTimers();openTimer.current=window.setTimeout(()=>{if(document.body.classList.contains("bv-toolbar-no-editor")&&document.body.classList.contains("bv-toolbar-no-quick"))return;const anchors=[...document.querySelectorAll<HTMLElement>(".bv-regional-action")].filter(item=>item.offsetParent!==null),anchor=requestedAnchor?.offsetParent?requestedAnchor:anchors[0];if(!anchor)return;setIncludeHidden(false);setPosition(positionLauncher(anchor,getColumns(false).filter(column=>column.items.length).length));setOpen(true)},delay)},[getColumns]);
    const show=useCallback(()=>reveal(180),[reveal]);
    const hide=useCallback(()=>{if(openTimer.current)window.clearTimeout(openTimer.current);const delay=Math.max(280,suppressHideUntil.current-Date.now());closeTimer.current=window.setTimeout(()=>{if(launcher.current?.matches(":hover"))return;setOpen(false);setIncludeHidden(false)},delay)},[]);
    useEffect(()=>{const attached=new Map<HTMLElement,()=>void>();const bind=()=>{for(const anchor of document.querySelectorAll<HTMLElement>(".bv-regional-action")){if(attached.has(anchor))continue;const enter=()=>show(),leave=()=>hide();anchor.addEventListener("pointerenter",enter);anchor.addEventListener("pointerleave",leave);const dispose=()=>{anchor.removeEventListener("pointerenter",enter);anchor.removeEventListener("pointerleave",leave)};attached.set(anchor,dispose)}};bind();const observer=new MutationObserver(bind);observer.observe(document.body,{childList:true,subtree:true});return()=>{observer.disconnect();attached.forEach(dispose=>dispose());clearTimers()}},[hide,show]);
    useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){setOpen(false);setIncludeHidden(false)}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[open]);
    useEffect(()=>{const toggle=(event:Event)=>open?(setOpen(false),setIncludeHidden(false)):reveal(0,(event as CustomEvent<{anchor?:HTMLElement}>).detail?.anchor);window.addEventListener(BV_TOOLBAR_LAUNCHER_TOGGLE_EVENT,toggle);return()=>window.removeEventListener(BV_TOOLBAR_LAUNCHER_TOGGLE_EVENT,toggle)},[open,reveal]);
    useEffect(()=>{const refresh=()=>setVisibilityRevision(value=>value+1);window.addEventListener(BV_WINDOW_VISIBILITY_CHANGED_EVENT,refresh);return()=>window.removeEventListener(BV_WINDOW_VISIBILITY_CHANGED_EVENT,refresh)},[]);
    const preserveLauncherFooter=(value:boolean)=>{clearTimers();suppressHideUntil.current=Date.now()+700;const before=launcher.current?.getBoundingClientRect();setIncludeHidden(value);requestAnimationFrame(()=>requestAnimationFrame(()=>{const after=launcher.current?.getBoundingClientRect();if(!before||!after)return;setPosition(current=>({...current,top:Math.max(12,Math.min(window.innerHeight-after.height-12,current.top+before.bottom-after.bottom))}))}))};
    if(!open)return null;
    const columns=getColumns(includeHidden).filter(column=>column.items.length);
    return createPortal(<div ref={launcher} className="bv-toolbar-window-launcher bv-ui bv-density-compact" style={{left:position.left,top:position.top,"--bv-launcher-columns":Math.max(1,columns.length)} as React.CSSProperties} role="dialog" aria-label="BV window launcher" onPointerEnter={clearTimers} onPointerLeave={hide}><div className="bv-toolbar-window-launcher__body">{columns.length?columns.map(column=><section key={column.id}><h3>{column.label}</h3><div>{column.items.map(item=><div key={item.id} className={`bv-toolbar-launcher-row ${item.hidden?"is-hidden":""}`}><Button intent="ghost" disabled={item.disabled} onClick={()=>{setOpen(false);setIncludeHidden(false);item.onSelect()}}><span>{item.label}</span>{item.meta&&<small>{item.meta}</small>}</Button>{item.secondary&&<button type="button" className="bv-toolbar-launcher-secondary" title={item.secondary.label} aria-label={item.secondary.label} onClick={()=>{setOpen(false);setIncludeHidden(false);item.secondary?.onSelect()}}>✎</button>}{item.hidden&&item.onReveal&&<button type="button" className="bv-toolbar-launcher-reveal" title="Show in BV window menus" aria-label={`Show ${item.label} in BV window menus`} onClick={item.onReveal}>◉</button>}</div>)}</div></section>):<div className="bv-toolbar-launcher-empty"><strong>No visible BV windows</strong><span>Show hidden nodes to restore one.</span></div>}</div><footer><ToggleField label="Show hidden nodes" value={includeHidden} trueLabel="Shown" falseLabel="Hidden" onValue={preserveLauncherFooter}/></footer></div>,document.body);
}
