[project]
name = "bv_nodepack"
version = "0.1.0"
description = "Advanced ComfyUI workflow toolkit featuring wireless, branchable Smart Pipes with ordered merges and Subgraph routing; user-defined group state controls; stable composable Subgraph UIs; a Subgraph-native seed controller; structured AST prompt processing; and flexible latent utilities."
authors = [
  {name = "BlackVortex", email = "blackvortexx@proton.me"}
]
readme = "README.md"
license = {text = "GNU General Public License v3"}


[project.urls]
Repository = "https://github.com/BlackVortexAI/bv_nodepack"
BugTracker = "https://github.com/BlackVortexAI/bv_nodepack/issues"
Documentation = "https://github.com/BlackVortexAI/bv_nodepack/wiki"


[tool.comfy]
PublisherId = "blackvortex"
DisplayName = "BV-NodePack"
Icon = ""
