import React,{ReactNode,useEffect,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import{Accordion,Badge,BooleanField,BoundsField,Breadcrumbs,Button,BvFooterActions,BvWindowFooter,BvWindowHeader,BvWindowNavigator,Callout,Card,CheckboxField,CodeBlock,ColorField,CommandPalette,ControlDensity,DataTable,DefinitionList,Dialog,Divider,EmptyState,ImagePicker,JsonEditor,Keybinding,KeybindingField,MenuButton,MultiSelect,NativePickerField,NumberField,OptionSet,Pagination,PanelFooter,PanelHeader,Progress,RichSelect,SearchField,Section,SecretField,SelectField,SortableItem,SortableList,SplitButton,Steps,Tabs,TagInput,TagSelect,TextareaField,TextField,Toast,ToastStack,ToggleField,Toolbar,Tooltip,UiDensity}from"./ui";
import{DetectorRegistryDialogView}from"./regional/DetectorRegistryDialogView";
import{DetailerPlanDialogView}from"./regional/DetailerPlanDialogView";

function ResizableDemo({title,children,width=420}:{title:string;children:ReactNode;width?:number}){return <article className="bv-resizable-demo" style={{width}}><header><strong>{title}</strong><small><span className="bv-responsive-state" aria-label="Current responsive state"/> · Drag the right edge</small></header><div>{children}</div></article>}

const options=[{value:"face",label:"Face detector",description:"Bounding-box model"},{value:"segment",label:"Segmentation",description:"Pixel-accurate mask"},{value:"pose",label:"Pose",description:"Keypoint detector"}];
const windowNodes=[{id:"regional-1",label:"Portrait workflow · #12"},{id:"regional-2",label:"Detail pass · #47"}];
function WindowContractDemo({node,onNode}:{node:string;onNode:(value:string)=>void}){const root=useRef<HTMLDivElement>(null),[width,setWidth]=useState(760),[visible,setVisible]=useState(true);useEffect(()=>{const element=root.current;if(!element)return;const observer=new ResizeObserver(entries=>setWidth(entries[0]?.contentRect.width??element.clientWidth));observer.observe(element);return()=>observer.disconnect()},[]);return <div ref={root} className="bv-window-contract-demo"><BvWindowHeader title="BV Regional Editor" shortTitle="Reg. Editor" menuVisible={visible} onMenuVisible={setVisible} context={<BvWindowNavigator label="Regional prompt document" value={node} options={windowNodes.map(item=>({value:item.id,label:item.label}))} onNavigate={value=>onNode(value)}/>} mode="floating" onMode={()=>{}} onMinimize={()=>{}} onClose={()=>{}}/><div className="bv-window-contract-body"><strong>Responsive window content</strong><span>Resize to see visibility, mode, node selection and title follow the production priority order.</span></div><BvWindowFooter status="Factory · Adjusted" actions={<BvFooterActions primary={<Button intent="primary">Save</Button>} secondary={<MenuButton label="Factory · Adjusted" actions={[{id:"factory",label:"Factory layout",onSelect:()=>{}},{id:"save",label:"Save as new layout…",onSelect:()=>{}}]}/>} overflow={[{id:"add",label:"Add item",onSelect:()=>{}},{id:"restore",label:"Restore defaults",onSelect:()=>{}}]}/>} stacked={width<700} minimal={width<470}/></div>}
function Demo(){
 const[text,setText]=useState("Regional prompt"),[number,setNumber]=useState(0.65),[flag,setFlag]=useState(true),[select,setSelect]=useState("face"),[tags,setTags]=useState(["regional","portrait"]),[multi,setMulti]=useState(["face"]),[color,setColor]=useState("#8D70FF"),[json,setJson]=useState('{\n  "enabled": true\n}'),[tab,setTab]=useState("properties"),[accordion,setAccordion]=useState(["basic"]),[page,setPage]=useState(2),[dialog,setDialog]=useState(false),[command,setCommand]=useState(false),[toast,setToast]=useState(true),[key,setKey]=useState<Keybinding>(),[items,setItems]=useState<SortableItem[]>([{id:"a",title:"Face refinement",description:"Detector job",content:<NumberField label="Guide size" value={24} min={1} max={64} step={1} unit="px" onValue={()=>{}}/>},{id:"b",title:"Hands refinement"}]);
 const [image,setImage]=useState("one");
 const[density,setDensity]=useState<ControlDensity>("compact");
 const[productionDialog,setProductionDialog]=useState<"detector"|"detailer">();
 const[windowNode,setWindowNode]=useState(windowNodes[0].id);
 const sections=["Density","Responsive","Windows","Foundations","Inputs","Selection","Feedback","Navigation","Content","Overlays","Data & media"];
 return <UiDensity density={density} className="bv-ui bv-showcase"><aside><h2>BV UI</h2>{sections.map(id=><a key={id} href={`#${id}`}>{id}</a>)}</aside><main><header><div><h1>BV UI Component Showcase</h1><p>Every example below renders the same internal React module used by production BV interfaces.</p></div><OptionSet label="Preview density" value={density} variant="segmented" options={[{value:"compact",label:"Compact"},{value:"comfortable",label:"Comfortable"}]} onValue={value=>setDensity(value as ControlDensity)}/></header>
 <Section id="Density" title="Density contract" description="The switch above applies to the complete component system." variant="outlined"><div className="bv-demo-grid"><Card title="Compact · panel default" description="Tool windows, sidebars and dense configuration surfaces">Conserves vertical space without reducing the global text size.</Card><Card title="Comfortable · writing default" description="Prompts, notes, dialogs and document-like surfaces">Adds room where reading and longer text entry matter more than density.</Card></div></Section>
 <Section id="Responsive" title="Responsive lab" description="Resize each isolated component surface; popups render through the viewport portal." variant="outlined"><div className="bv-responsive-lab"><ResizableDemo title="Adaptive fields"><TextField label="Output name" value={text} icon="↔" onValue={setText}/><TextareaField label="Regional prompt" value={text} icon="≡" onValue={setText}/><NumberField label="Strength" value={number} min={0} max={1} step={.01} unit="×" onValue={setNumber}/><ColorField label="Display color" value={color} onValue={setColor}/></ResizableDemo><ResizableDemo title="Navigation" width={520}><Tabs items={[{id:"properties",label:"Properties",content:"Focused controls"},{id:"help",label:"Help",content:"Context help"}]} value={tab} onValue={setTab}/><Accordion exclusive items={[{id:"basic",title:"Basic",content:"Common settings"},{id:"advanced",title:"Advanced",content:"Optional settings"}]} value={accordion} onValue={setAccordion}/><Pagination page={page} pages={5} onPage={setPage}/><Steps current={1} items={[{label:"Select"},{label:"Configure"},{label:"Apply"}]}/></ResizableDemo><ResizableDemo title="Data and popup surfaces" width={520}><DefinitionList items={[{term:"Region Usage",description:"Generation, Detailer or Both"},{term:"Detector Binding",description:"Stable detector assignment"}]}/><DataTable rows={options} rowKey={row=>row.value} columns={[{id:"name",header:"Name",cell:row=>row.label},{id:"detail",header:"Description",cell:row=>row.description}]}/><ImagePicker label="Queue image" value={image} onValue={setImage} options={[{id:"one",name:"Sender 1",meta:"Latest",src:"./assets/workflow-canvas.png"},{id:"two",name:"Sender 2",meta:"Earlier",src:"./assets/workflow-canvas.png"}]}/></ResizableDemo></div></Section>
 <Section id="Windows" title="Window system" description="Canonical responsive header, multi-instance navigation and footer action hierarchy." variant="outlined"><ResizableDemo title="Managed window contract" width={760}><WindowContractDemo node={windowNode} onNode={setWindowNode}/></ResizableDemo></Section>
 <Section id="Foundations" title="Foundations" description="Tokens, surfaces, buttons and scalable system typography" variant="outlined"><div className="bv-demo-grid"><Card title="Surface" description="Shared radius, border and spacing">System font · inherited size modes</Card><div><Button intent="primary">Primary</Button> <Button>Secondary</Button> <Button intent="danger">Danger</Button> <Button intent="ghost">Ghost</Button></div><Toolbar items={[{id:"select",label:"Select",icon:"↖",active:true,onSelect:()=>{}},{id:"brush",label:"Brush",icon:"⌁",onSelect:()=>{}}]}/><div className="bv-panel-demo"><PanelHeader title="Prompt panel" subtitle="Canonical compact panel chrome" icon={<span aria-hidden="true">✦</span>}/><div>Panel content uses the shared spacing and density contract.</div><PanelFooter status={<Badge tone="success" dot>Autosaved</Badge>} actions={<Button intent="primary">Open editor</Button>}/></div></div></Section>
 <Section id="Inputs" title="Inputs" variant="outlined"><div className="bv-demo-grid"><TextField label="Text input" value={text} icon="↔" onValue={setText}/><TextareaField label="Textarea" value={text} icon="≡" onValue={setText}/><NumberField label="Strength" value={number} min={0} max={1} step={.01} unit="×" onValue={setNumber}/><BoundsField label="Bounds" value={{x:0,y:0,width:1024,height:1024}} onValue={()=>{}}/><SecretField label="Provider API key" value="demo-secret" onValue={()=>{}}/><NativePickerField label="Model file" value="detector.pt" onValue={()=>{}}/><KeybindingField label="Open editor" value={key} onValue={setKey}/><ColorField label="Display color" value={color} onValue={setColor}/><JsonEditor label="Configuration" value={json} onValue={setJson}/></div></Section>
 <Section id="Selection" title="Selection" variant="outlined"><div className="bv-demo-grid"><ToggleField label="Preview" value={flag} onValue={setFlag}/><CheckboxField label="Enable output" checked={flag} onValue={setFlag}/><BooleanField variant="select" label="Return mask" value={flag} onValue={setFlag}/><SelectField label="Detector" value={select} options={options} onValue={setSelect}/><RichSelect label="Rich detector" value={select} options={options} onValue={setSelect}/><OptionSet label="Usage" value="both" variant="segmented" options={[{value:"generation",label:"Generation"},{value:"detailer",label:"Detailer"},{value:"both",label:"Both"}]} onValue={()=>{}}/><TagInput label="Tags" value={tags} onValue={setTags} suggestions={["foreground","quality"]}/><TagSelect label="Regions" value={multi} options={options} minSelected={1} onValue={setMulti}/><MultiSelect label="Detectors" value={multi} options={options} onValue={setMulti} searchable/><SearchField label="Search" value={text} onValue={setText} options={options} onSelect={item=>setSelect(item.value)} mode="fuzzy"/></div></Section>
 <Section id="Feedback" title="Feedback" variant="outlined"><Callout tone="info" title="Information">Canvas remains interactive behind modeless BV windows.</Callout><Callout tone="warning" title="Review">One detector assignment is incomplete.</Callout><Progress label="Processing regions" value={.64}/><EmptyState title="No queue images" description="Run the workflow to receive images."/><Badge tone="success">Ready</Badge>{toast&&<ToastStack><Toast tone="success" title="Layout saved" onClose={()=>setToast(false)}/></ToastStack>}</Section>
 <Section id="Navigation" title="Navigation" variant="outlined"><Breadcrumbs items={[{label:"Editor",onClick:()=>{}},{label:"Regions"}]}/><Tabs items={[{id:"properties",label:"Properties",content:"Focused controls"},{id:"help",label:"Help",content:"Context help"}]} value={tab} onValue={setTab}/><Accordion exclusive items={[{id:"basic",title:"Basic",content:"Common settings"},{id:"advanced",title:"Advanced",content:"Optional settings"}]} value={accordion} onValue={setAccordion}/><Pagination page={page} pages={5} onPage={setPage}/><Steps current={1} items={[{label:"Select"},{label:"Configure"},{label:"Apply"}]}/><Tooltip content="Brush tool · B"><Button iconOnly>⌁</Button></Tooltip></Section>
 <Section id="Content" title="Content" variant="outlined"><CodeBlock language="json" lineNumbers code={json}/><DefinitionList items={[{term:"Region Usage",description:"Generation, Detailer or Both"},{term:"Detector Binding",description:"Stable detector assignment"}]}/><Divider label="Advanced settings"/><DataTable rows={options} rowKey={row=>row.value} columns={[{id:"name",header:"Name",cell:row=>row.label},{id:"detail",header:"Description",cell:row=>row.description}]}/></Section>
 <Section id="Overlays" title="Overlays" variant="outlined"><div className="bv-demo-actions"><Button onClick={()=>setDialog(true)}>Open dialog</Button><Button onClick={()=>setProductionDialog("detector")}>Detector Registry</Button><Button onClick={()=>setProductionDialog("detailer")}>Detailer Plan</Button><Button onClick={()=>setCommand(true)}>Command palette</Button><MenuButton label="Export" actions={[{id:"json",label:"Export JSON",onSelect:()=>{}}]}/><SplitButton label="Run plan" onClick={()=>{}} actions={[{id:"dry",label:"Dry run",onSelect:()=>{}}]}/></div><Dialog open={dialog} title="Confirm changes" onClose={()=>setDialog(false)} footer={<Button intent="primary" onClick={()=>setDialog(false)}>Apply</Button>}>Shared dialog chrome and focus surface.</Dialog>{productionDialog==="detector"&&<DetectorRegistryDialogView nodeId={windowNode} nodes={windowNodes} onNavigate={value=>setWindowNode(value)} catalog={{ultralytics:["bbox/face_yolov8m.pt","segm/person_yolov8m-seg.pt"],onnx:["face_detector.onnx"],sam:["sam_vit_b_01ec64.pth"]}} stored={JSON.stringify({detectors:[{id:"face-detail",provider:"ultralytics",model_name:"bbox/face_yolov8m.pt"},{id:"person-mask",provider:"ultralytics",model_name:"segm/person_yolov8m-seg.pt",sam_model_name:"sam_vit_b_01ec64.pth",sam_device_mode:"AUTO"}]})} save={()=>{}} close={()=>setProductionDialog(undefined)}/>} {productionDialog==="detailer"&&<DetailerPlanDialogView nodeId={windowNode} nodes={windowNodes} onNavigate={value=>setWindowNode(value)} regions={[{id:"face",name:"Face",priority:0,usage:"both"},{id:"hands",name:"Hands",priority:1,usage:"detailer"},{id:"garment",name:"Garment",priority:2,usage:"both"}]} detectorIds={["face-detail","person-mask"]} stored={JSON.stringify({jobs:[{region_ids:["face","hands"],primary_region_id:"face",mask_composition:"union",prompt_composition:"context",detector_id:"face-detail",conditioning:{global_influence:1,background_influence:.35,primary_region_influence:1,context_region_influence:.8},detector:{roi_padding:.15,threshold:.5,dilation:0,crop_factor:1.5,drop_size:10}},{region_ids:["garment"],primary_region_id:"garment",mask_composition:"union",prompt_composition:"primary",detector_id:"person-mask",conditioning:{global_influence:1,background_influence:.35,primary_region_influence:1,context_region_influence:1},detector:{roi_padding:.2,threshold:.55,dilation:4,crop_factor:1.8,drop_size:10}}]})} save={()=>{}} close={()=>setProductionDialog(undefined)}/>}<CommandPalette open={command} onClose={()=>setCommand(false)} commands={[{id:"reset",label:"Reset layout",run:()=>{}},{id:"float",label:"Float selected tab",run:()=>{}}]}/></Section>
 <Section id="Data & media" title="Data & media" variant="outlined"><SortableList items={items} onReorder={setItems}/><ImagePicker label="Queue image" value={image} onValue={setImage} options={[{id:"one",name:"Sender 1",meta:"Latest",src:"./assets/workflow-canvas.png"},{id:"two",name:"Sender 2",meta:"Earlier",src:"./assets/workflow-canvas.png"}]}/></Section>
 </main></UiDensity>;
}
document.body.replaceChildren();createRoot(document.body.appendChild(document.createElement("div"))).render(<Demo/>);
