import assert from "node:assert/strict";
import test from "node:test";
import {detailerV3Catalog,reconcileDetailerPromptV3Now,reconcileDetailerV3Now} from "../ui/src/regional/detailerV3Graph.ts";

globalThis.window={dispatchEvent(){}};globalThis.CustomEvent=class{constructor(type,init){this.type=type;this.detail=init?.detail}};
const collectorConfig=(id,resources)=>JSON.stringify({schema:"bv.detector_registry_config",version:2,collector_id:id,detectors:resources.map(resource=>({id:resource,provider:"ultralytics",model_name:`${resource}.pt`}))});
function graphNodes(){const graph={_nodes:[],_links:new Map(),getNodeById(id){return this._nodes.find(node=>node.id===id)}};let next=1;const node=(id,type,config)=>{const value={id,type,comfyClass:type,graph,inputs:[],outputs:type==="BV Detector Registry"?[{name:"detector_registry",type:"BV_DETECTOR_REGISTRY",links:[]},{name:"count",type:"INT",links:[]},{name:"summary",type:"STRING",links:[]},{name:"resource_provider",type:"BV_RUNTIME_RESOURCE_PROVIDER",links:[]}]:[],widgets:[{name:"config_json",value:config}],addInput(name,type){this.inputs.push({name,type,link:null})},removeInput(index){this.inputs.splice(index,1)},disconnectInput(index){const linkId=this.inputs[index].link,link=graph._links.get(linkId);if(link){const source=graph.getNodeById(link.origin_id),output=source.outputs[link.origin_slot];output.links=output.links.filter(id=>id!==linkId);graph._links.delete(linkId)}this.inputs[index].link=null},connect(output,target,input){const link={id:next++,origin_id:this.id,origin_slot:output,target_id:target.id,target_slot:input};graph._links.set(link.id,link);this.outputs[output].links.push(link.id);target.inputs[input].link=link.id}};graph._nodes.push(value);return value};return{graph,node};}

test("detailer plan persists two independent same-graph collector links",()=>{const{node}=graphNodes(),a=node(1,"BV Detector Registry",collectorConfig("collector-a",["face"])),b=node(2,"BV Detector Registry",collectorConfig("collector-b",["eyes"])),plan=node(3,"BV Regional Detailer Plan",JSON.stringify({version:1,jobs:[{id:"face",detector_assignments:[{id:"a",source:{collector_id:"collector-a",resource_id:"face"},options:{}}]},{id:"eyes",detector_assignments:[{id:"b",source:{collector_id:"collector-b",resource_id:"eyes"},options:{}}]}]}));reconcileDetailerV3Now(plan);assert.equal(plan.inputs.length,2);assert.equal(plan.inputs[0].link!=null,true);assert.equal(plan.inputs[1].link!=null,true);assert.equal(a.outputs[3].links.length,1);assert.equal(b.outputs[3].links.length,1)});

test("collector labels remain distinct when nodes keep their default title",()=>{const{node}=graphNodes();node(1,"BV Detector Registry",collectorConfig("collector-a",["face"]));node(2,"BV Detector Registry",collectorConfig("collector-b",["eyes"]));const plan=node(3,"BV Regional Detailer Plan",JSON.stringify({version:1,jobs:[]}));assert.deepEqual(detailerV3Catalog(plan).map(item=>item.label),["BV Detector Registry · #1","BV Detector Registry · #2"])});

test("catalog uses concrete graph ownership when renderer nodes lack graph backpointers",()=>{const{graph,node}=graphNodes(),collector=node(1,"BV Detector Registry",collectorConfig("collector-a",["face"])),plan=node(2,"BV Regional Detailer Plan",JSON.stringify({version:1,jobs:[]}));collector.__bvConcreteGraph=graph;plan.__bvConcreteGraph=graph;delete collector.graph;delete plan.graph;assert.deepEqual(detailerV3Catalog(plan).map(item=>item.resources[0].id),["face"])});

test("shrinking assignments disconnects and removes surplus provider inputs",()=>{const{node}=graphNodes(),a=node(1,"BV Detector Registry",collectorConfig("collector-a",["face"])),b=node(2,"BV Detector Registry",collectorConfig("collector-b",["eyes"])),plan=node(3,"BV Regional Detailer Plan",JSON.stringify({version:1,jobs:[{id:"face",detector_assignments:[{id:"a",source:{collector_id:"collector-a",resource_id:"face"},options:{}}]},{id:"eyes",detector_assignments:[{id:"b",source:{collector_id:"collector-b",resource_id:"eyes"},options:{}}]}]}));reconcileDetailerV3Now(plan);plan.widgets[0].value=JSON.stringify({version:1,jobs:[{id:"face",detector_assignments:[{id:"a",source:{collector_id:"collector-a",resource_id:"face"},options:{}}]}]});reconcileDetailerV3Now(plan);assert.equal(a.outputs[3].links.length,1);assert.equal(b.outputs[3].links.length,0);assert.equal(plan.inputs.length,1)});

test("Regional Prompt easy mode persists its collector link and propagates it to a downstream empty plan",()=>{const{graph,node}=graphNodes(),collector=node(1,"BV Detector Registry",collectorConfig("collector-a",["face"])),prompt=node(2,"BV Regional Prompt",JSON.stringify({version:1,jobs:[]})),plan=node(3,"BV Regional Detailer Plan","");prompt.widgets=[{name:"detailer_v3_config_json",value:JSON.stringify({version:1,jobs:[{id:"face",detector_assignments:[{id:"a",source:{collector_id:"collector-a",resource_id:"face"},options:{}}]}]})}];prompt.outputs=[{name:"regional",type:"BV_REGIONAL",links:[]}];plan.inputs=[{name:"regional_prompt",type:"BV_REGIONAL",link:null}];prompt.connect(0,plan,0);reconcileDetailerPromptV3Now(prompt);reconcileDetailerV3Now(plan);assert.ok(prompt.inputs.find(input=>input.name==="detailer_resource_provider_1")?.link!=null);assert.ok(plan.inputs.find(input=>input.name==="resource_provider")?.link!=null);assert.equal(collector.outputs[3].links.length,2);assert.equal(graph._links.size,3)});
