import assert from "node:assert/strict";
import test from "node:test";
import {lutV3Catalog,prepareLutRegistryV3,reconcileLutV3Now} from "../ui/src/regional/lutV3Catalog.ts";

globalThis.window={dispatchEvent(){}};globalThis.CustomEvent=class{constructor(type,init){this.type=type;this.detail=init?.detail}};
const widget=(name,value)=>({name,value,type:"text",computeSize:()=>[120,20]});
function fixture(){const graph={_nodes:[],_links:new Map(),getNodeById(id){return this._nodes.find(node=>node.id===id)}};let next=1;const node=(id,type,widgets=[])=>{const value={id,type,comfyClass:type,title:type,graph,widgets,inputs:[],outputs:[],addInput(name,type){this.inputs.push({name,type,link:null})},addOutput(name,type){this.outputs.push({name,type,links:[]})},removeInput(index){this.inputs.splice(index,1)},disconnectInput(index){this.inputs[index].link=null},connect(output,target,input){const link={id:next++,origin_id:id,origin_slot:output,target_id:target.id,target_slot:input};graph._links.set(link.id,link);this.outputs[output].links.push(link.id);target.inputs[input].link=link.id}};graph._nodes.push(value);return value};return{graph,node};}

test("single LUT Registry replaces the regional named-LUT collector chain",()=>{const{node}=fixture(),registry=node(1,"BV LUT Registry",[widget("config_json",JSON.stringify({schema:"bv.lut_registry_config",version:1,collector_id:"11111111-1111-4111-8111-111111111111",luts:[{id:"warm",lut_name:"Built-in: Warm Contrast"}]}))]),plan=node(2,"BV Regional LUT Plan",[widget("config_json",JSON.stringify({version:1,jobs:[{lut_source:{collector_id:"11111111-1111-4111-8111-111111111111",resource_id:"warm"}}]}))]);prepareLutRegistryV3(registry);reconcileLutV3Now(plan);assert.deepEqual(lutV3Catalog(plan)[0].resources,[{id:"warm",label:"warm · Built-in: Warm Contrast"}]);assert.ok(plan.inputs.find(item=>item.name==="resource_provider_1")?.link!=null);});

test("easy Regional Prompt connects directly to Loop Start and receives one native provider link",()=>{const{node}=fixture(),registry=node(1,"BV LUT Registry",[widget("config_json",JSON.stringify({schema:"bv.lut_registry_config",version:1,collector_id:"11111111-1111-4111-8111-111111111111",luts:[{id:"warm",lut_name:"Built-in: Warm Contrast"}]}))]),prompt=node(2,"BV Regional Prompt",[widget("lut_v3_config_json",JSON.stringify({version:1,jobs:[{lut_source:{collector_id:"11111111-1111-4111-8111-111111111111",resource_id:"warm"}}]}))]),start=node(3,"BV LUT Loop Start",[]);prompt.outputs=[{name:"regional",type:"BV_REGIONAL",links:[]}];start.inputs=[{name:"plan",type:"*",link:null}];prompt.connect(0,start,0);prepareLutRegistryV3(registry);reconcileLutV3Now(start);const provider=start.inputs.find(item=>item.name==="resource_provider_1");assert.ok(provider?.link!=null);assert.equal(provider.__bvM0ResourceSlot,true);});

test("Loop Start retains LUT providers when its Regional LUT Plan is bypassed",()=>{const{node}=fixture(),id="11111111-1111-4111-8111-111111111111",registry=node(1,"BV LUT Registry",[widget("config_json",JSON.stringify({schema:"bv.lut_registry_config",version:1,collector_id:id,luts:[{id:"warm",lut_name:"Built-in: Warm Contrast"}]}))]),plan=node(2,"BV Regional LUT Plan",[widget("config_json",JSON.stringify({version:1,jobs:[{lut_source:{collector_id:id,resource_id:"warm"}}]}))]),start=node(3,"BV LUT Loop Start",[]);plan.outputs=[{name:"lut_plan",type:"BV_LUT_PLAN",links:[]}];start.inputs=[{name:"plan",type:"*",link:null}];plan.connect(0,start,0);prepareLutRegistryV3(registry);reconcileLutV3Now(start);const provider=start.inputs.find(item=>item.name==="resource_provider_1");assert.ok(provider?.link!=null);assert.equal(provider.__bvM0ResourceSlot,true);});

test("Regional LUT consumers mark every provider for one visual fan-in",()=>{const{node}=fixture(),first="11111111-1111-4111-8111-111111111111",second="22222222-2222-4222-8222-222222222222",a=node(1,"BV LUT Registry",[widget("config_json",JSON.stringify({schema:"bv.lut_registry_config",version:1,collector_id:first,luts:[{id:"warm",lut_name:"Built-in: Warm Contrast"}]}))]),b=node(2,"BV LUT Registry",[widget("config_json",JSON.stringify({schema:"bv.lut_registry_config",version:1,collector_id:second,luts:[{id:"cool",lut_name:"Built-in: Cool Graphite"}]}))]),plan=node(3,"BV Regional LUT Plan",[widget("config_json",JSON.stringify({version:1,jobs:[{lut_source:{collector_id:first,resource_id:"warm"}},{lut_source:{collector_id:second,resource_id:"cool"}}]}))]);prepareLutRegistryV3(a);prepareLutRegistryV3(b);reconcileLutV3Now(plan);const providers=plan.inputs.filter(item=>item.name.startsWith("resource_provider_"));assert.equal(providers.length,2);assert.equal(providers.every(item=>item.__bvM0ResourceSlot&&item.__bvM0PortHidden),true);});
