import React,{useEffect,useMemo,useState}from"react";
import { Button, Callout, DefinitionList, NumberField, SelectField, ToggleField } from "../ui/components";
import { BvFooterActions, BvManagedWindow } from "../ui/window";
import { getUiCaptureSource, listUiCaptureSources } from "./captureRegistry";
import { BV_EXPORT_OPEN_EVENT, type ExportOpenDetail } from "./events";
import { captureGraph, graphExportBounds, resolveGraphSubject } from "./graphCapture";
import { normalizeExportOptions, safeFilename, suggestedFilename, type ExportBackground, type ExportOptions, type ExportScale } from "./model";
import { saveExport } from "./save";
import { captureUi, uiExportBounds } from "./uiCapture";

const KEY="bv.export.preferences.v1";
const readPreferences=()=>{try{return normalizeExportOptions(JSON.parse(sessionStorage.getItem(KEY)??"{}"))}catch{return normalizeExportOptions()}};
export const captureExport=(app:any,options:ExportOptions)=>options.source?.startsWith("ui:")?captureUi(app,options.source.slice(3),options):captureGraph(app,options);

export function ExportDialog({app,api}:{app:any;api:any}){
    const [open,setOpen]=useState(false),[options,setOptions]=useState(readPreferences),[busy,setBusy]=useState(false),[error,setError]=useState(""),[revision,setRevision]=useState(0);
    useEffect(()=>{const show=(event:Event)=>{const requested=(event as CustomEvent<ExportOpenDetail>).detail?.source,subject=resolveGraphSubject(app),fallback=subject.selectedNodes.size||subject.selectedGroups.size?"selection":"graph";setOptions(current=>({...current,source:requested??fallback}));setError("");setRevision(value=>value+1);setOpen(true)};window.addEventListener(BV_EXPORT_OPEN_EVENT,show);return()=>window.removeEventListener(BV_EXPORT_OPEN_EVENT,show)},[app]);
    const uiSources=useMemo(()=>listUiCaptureSources(),[open,revision]),sourceOptions=[{value:"graph",label:"Entire active graph"},{value:"selection",label:"Selected nodes and groups"},...uiSources.map(source=>({value:`ui:${source.id}`,label:`BV UI · ${source.title}`}))];
    const summary=useMemo(()=>{try{const normalized=normalizeExportOptions(options),bounds=normalized.source.startsWith("ui:")?uiExportBounds(normalized.source.slice(3),normalized.padding):graphExportBounds(resolveGraphSubject(app),normalized.source==="selection"?"selection":"graph",normalized.padding);return `${Math.ceil(bounds.width*normalized.scale)} × ${Math.ceil(bounds.height*normalized.scale)} px`}catch(reason){return reason instanceof Error?reason.message:String(reason)}},[app,options,revision]);
    const update=(next:Partial<typeof options>)=>setOptions(current=>{const updated={...current,...next};sessionStorage.setItem(KEY,JSON.stringify(updated));return updated});
    const filename=()=>{if(options.filename)return options.filename;const workflowName=String(app?.workflowManager?.activeWorkflow?.filename??app?.workflowManager?.activeWorkflow?.name??"workflow"),source=options.source??"graph";if(source.startsWith("ui:")){const title=getUiCaptureSource(source.slice(3))?.title??"bv-ui";return suggestedFilename(workflowName,`ui:${safeFilename(title,"bv-ui")}`)}const subject=resolveGraphSubject(app);return suggestedFilename(workflowName,source,subject.isSubgraph?subject.subgraphName:undefined)};
    const run=async()=>{setBusy(true);setError("");try{const queue=await api.getQueue();if(queue.Running?.length||queue.Pending?.length)throw new Error("Export is disabled while the ComfyUI queue is active.");sessionStorage.setItem(KEY,JSON.stringify(options));await saveExport(await captureExport(app,{...options,filename:filename()}));setOpen(false)}catch(reason){if((reason as any)?.name!=="AbortError")setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};
    const close=()=>!busy&&setOpen(false);
    return <div data-bv-export-ui><BvManagedWindow open={open} activationToken={revision} title="Export image" shortTitle="Export" initialGeometry={{width:680,height:620}} minSize={{width:420,height:420}} footerStackAt={540} onClose={close} status={busy?"Rendering PNG…":error?"Export failed":`${summary} · PNG`} actions={<BvFooterActions primary={<Button intent="primary" loading={busy} onClick={run}>Export PNG…</Button>} secondary={<Button intent="ghost" disabled={busy} onClick={close}>Cancel</Button>}/> }>
        <div className="bv-ui-stack bv-export-dialog"><p>Render the current graph scope or an open BV interface as a deterministic PNG.</p><SelectField label="Source" value={options.source} options={sourceOptions} onValue={value=>update({source:value as typeof options.source})}/><SelectField label="Background" value={options.background} options={[{value:"transparent",label:"Transparent"},{value:"bv-grid",label:"BV Documentation grid"},{value:"comfyui",label:"Current ComfyUI background"}]} onValue={value=>update({background:value as ExportBackground})}/><SelectField label="Scale" value={String(options.scale)} options={[1,2,3].map(value=>({value:String(value),label:`${value}×`}))} onValue={value=>update({scale:Number(value) as ExportScale})}/><NumberField label="Outer padding" value={options.padding} min={0} max={256} step={1} unit="px" slider={false} onValue={padding=>update({padding})}/><ToggleField label="PNG metadata" value={options.embedWorkflow} trueLabel="Complete workflow embedded" falseLabel="No workflow metadata" onValue={embedWorkflow=>update({embedWorkflow})}/><DefinitionList compact items={[{term:"Output",description:summary},{term:"Format",description:"PNG · tight bounds · no transient focus state"}]}/>{error&&<Callout tone="danger" title="Export failed">{error}</Callout>}</div>
    </BvManagedWindow></div>;
}
