import React, { ReactNode, useRef, useState } from "react";
import { AnchoredPopover } from "./floating";

export type ButtonIntent="primary"|"secondary"|"ghost"|"danger"|"warning"|"success"|"info";
export type ControlDensity="comfortable"|"compact";
export function UiDensity({density="compact",className="",children}:{density?:ControlDensity;className?:string;children:ReactNode}){return <div className={`bv-density-${density} ${className}`.trim()}>{children}</div>}
export type ButtonProps=React.ButtonHTMLAttributes<HTMLButtonElement>&{intent?:ButtonIntent;icon?:ReactNode;iconOnly?:boolean;loading?:boolean;density?:ControlDensity};
export function Button({intent="secondary",icon,iconOnly=false,loading=false,density,className="",children,disabled,...props}:ButtonProps){return <button {...props} disabled={disabled||loading} className={`bv-button ${intent} ${density?`bv-density-${density}`:""} ${iconOnly?"icon-only":""} ${className}`.trim()}>{loading?<span className="bv-spinner"/>:iconOnly?(icon??children):icon}{!iconOnly&&children}</button>;}
export type MenuAction={id:string;label:string;icon?:ReactNode;disabled?:boolean;danger?:boolean;shortcut?:string;separatorBefore?:boolean;onSelect:()=>void};
export function Menu({actions,onClose}:{actions:MenuAction[];onClose?:()=>void}){return <div className="bv-menu-content" role="menu">{actions.map(action=><React.Fragment key={action.id}>{action.separatorBefore&&<hr/>}<button type="button" role="menuitem" disabled={action.disabled} className={action.danger?"danger":""} onClick={()=>{action.onSelect();onClose?.();}}>{action.icon}<span>{action.label}</span>{action.shortcut&&<kbd>{action.shortcut}</kbd>}</button></React.Fragment>)}</div>}
export function MenuButton({label,actions,intent="secondary",icon,density}:{label:string;actions:MenuAction[];intent?:ButtonIntent;icon?:ReactNode;density?:ControlDensity}){const[open,setOpen]=useState(false),anchor=useRef<HTMLDivElement>(null);return <div className="bv-menu-button" ref={anchor}><Button intent={intent} icon={icon} density={density} aria-haspopup="menu" aria-expanded={open} onClick={()=>setOpen(!open)}>{label}<span className="bv-chevron"/></Button><AnchoredPopover open={open} anchor={anchor} onClose={()=>setOpen(false)} className="bv-menu"><Menu actions={actions} onClose={()=>setOpen(false)}/></AnchoredPopover></div>}export function SplitButton({label,onClick,actions,intent="primary",icon,density}:{label:string;onClick:()=>void;actions:MenuAction[];intent?:ButtonIntent;icon?:ReactNode;density?:ControlDensity}){const[open,setOpen]=useState(false),anchor=useRef<HTMLDivElement>(null);return <div ref={anchor} className="bv-split-button"><Button intent={intent} icon={icon} density={density} onClick={onClick}>{label}</Button><Button intent={intent} density={density} icon={<span className="bv-chevron"/>} iconOnly aria-label={`More ${label} options`} aria-expanded={open} onClick={()=>setOpen(!open)}/><AnchoredPopover open={open} anchor={anchor} onClose={()=>setOpen(false)} className="bv-menu"><Menu actions={actions} onClose={()=>setOpen(false)}/></AnchoredPopover></div>}export type ToolbarItem={id:string;label:string;icon:ReactNode;active?:boolean;disabled?:boolean;onSelect:()=>void;group?:string};
export function Toolbar({items,orientation="horizontal",label="Tools",overflow=[],density}:{items:ToolbarItem[];orientation?:"horizontal"|"vertical";label?:string;overflow?:MenuAction[];density?:ControlDensity}){return <div className={`bv-toolbar ${orientation}`} role="toolbar" aria-orientation={orientation} aria-label={label}>{items.map((item,index)=><React.Fragment key={item.id}>{index>0&&item.group!==items[index-1].group&&<span className="bv-toolbar-divider"/>}<Button intent="ghost" density={density} icon={item.icon} iconOnly={orientation==="vertical"} aria-label={item.label} aria-pressed={item.active} disabled={item.disabled} className={item.active?"active":""} onClick={item.onSelect}>{item.label}</Button></React.Fragment>)}{overflow.length>0&&<MenuButton label="More" actions={overflow} intent="ghost" density={density}/>}</div>}
