import React,{ReactNode,useState}from"react";
import{Button}from"./actions";
export function Section({id,title,description,icon,actions,children,variant="plain"}:{id?:string;title?:ReactNode;description?:ReactNode;icon?:ReactNode;actions?:ReactNode;children:ReactNode;variant?:"plain"|"outlined"|"raised"}){return <section id={id} className={`bv-section ${variant}`}>{(title||description||actions)&&<header>{icon&&<span className="bv-section-icon">{icon}</span>}<div>{title&&<h3>{title}</h3>}{description&&<p>{description}</p>}</div>{actions&&<div className="bv-section-actions">{actions}</div>}</header>}<div className="bv-section-body">{children}</div></section>}
export function Card({title,description,icon,actions,children,interactive=false,onClick}:{title?:ReactNode;description?:ReactNode;icon?:ReactNode;actions?:ReactNode;children?:ReactNode;interactive?:boolean;onClick?:()=>void}){const content=<>{(title||description||actions)&&<header>{icon}<div>{title&&<strong>{title}</strong>}{description&&<small>{description}</small>}</div>{actions}</header>}{children&&<div>{children}</div>}</>;return interactive?<button type="button" className="bv-card interactive" onClick={onClick}>{content}</button>:<article className="bv-card">{content}</article>}
export function Divider({label,orientation="horizontal"}:{label?:ReactNode;orientation?:"horizontal"|"vertical"}){return <div className={`bv-divider ${orientation}`}>{label&&<span>{label}</span>}</div>}
export function CodeBlock({code,language="text",lineNumbers=false,copyable=true}:{code:string;language?:string;lineNumbers?:boolean;copyable?:boolean}){const[copied,setCopied]=useState(false);const copy=async()=>{await navigator.clipboard?.writeText(code);setCopied(true);setTimeout(()=>setCopied(false),1200)};return <div className={`bv-code-block ${lineNumbers?"line-numbers":""}`}><header><span>{language.toUpperCase()}</span>{copyable&&<Button intent="ghost" onClick={copy}>{copied?"Copied":"Copy"}</Button>}</header><pre><code>{code.split("\n").map((line,i)=><span className="bv-code-line" key={i}>{line}{"\n"}</span>)}</code></pre></div>}
export function TruncatedCopyText({text,label="Text",maxLength=120,wrap=false}:{text:string;label?:string;maxLength?:number;wrap?:boolean}){const[copied,setCopied]=useState(false),limit=Math.max(1,maxLength),truncated=!wrap&&text.length>limit,preview=truncated?text.slice(0,limit).trimEnd()+"…":text,copy=async()=>{if(!navigator.clipboard?.writeText)return;try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1200)}catch{return}};return <div className="bv-truncated-copy"><span className={`bv-truncated-copy-value${wrap?" wrap":""}`} title={text}>{preview}</span><Button density="compact" intent="ghost" aria-label={'Copy '+label} onPointerDown={event=>event.stopPropagation()} onClick={event=>{event.stopPropagation();void copy()}}>{copied?"Copied":"Copy"}</Button></div>}
export function Quote({children,cite}:{children:ReactNode;cite?:ReactNode}){return <figure className="bv-quote"><blockquote>{children}</blockquote>{cite&&<figcaption>{cite}</figcaption>}</figure>}
export function DataTable<T>({columns,rows,rowKey,striped=false,compact=false}:{columns:Array<{id:string;header:ReactNode;cell:(row:T)=>ReactNode;numeric?:boolean}>;rows:T[];rowKey:(row:T)=>React.Key;striped?:boolean;compact?:boolean}){return <div className="bv-table-scroll"><table className={`${striped?"striped":""} ${compact?"compact":""}`}><thead><tr>{columns.map(column=><th key={column.id} className={column.numeric?"numeric":""}>{column.header}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={rowKey(row)}>{columns.map(column=><td key={column.id} className={column.numeric?"numeric":""}>{column.cell(row)}</td>)}</tr>)}</tbody></table></div>}
export function DefinitionList({items,compact=false}:{items:Array<{term:ReactNode;description:ReactNode}>;compact?:boolean}){return <dl className={`bv-definition-list ${compact?"compact":""}`}>{items.map((item,i)=><div className="bv-definition-row" key={i}><dt>{item.term}</dt><dd>{item.description}</dd></div>)}</dl>}
export function PanelHeader({title,icon,subtitle,actions,...props}:{title:ReactNode;icon?:ReactNode;subtitle?:ReactNode;actions?:ReactNode}&React.HTMLAttributes<HTMLElement>){return <header {...props} className={`bv-panel-header ${props.className??""}`}>{icon}<div><strong>{title}</strong>{subtitle&&<small>{subtitle}</small>}</div>{actions&&<div className="bv-panel-actions">{actions}</div>}</header>}
export function PanelFooter({status,actions,className=""}:{status?:ReactNode;actions?:ReactNode;className?:string}){return <footer className={`bv-panel-footer ${className}`.trim()}>{status&&<div className="bv-panel-status">{status}</div>}{actions&&<div className="bv-panel-actions">{actions}</div>}</footer>}
