import React,{CSSProperties,ReactNode,useEffect,useRef,useState}from"react";
import{Button,Menu,type MenuAction}from"./actions";
import{AnchoredPopover,ContextMenu,Popover,Portal}from"./overlays";
import{fitHoverPreviewSize,HOVER_PREVIEW_MAX_SIZE,placeHoverPreview,reorderByStableId,type StableIdItem}from"./compactInteractions";
export type SortableItem={id:string;title:ReactNode;label?:string;description?:ReactNode;summary?:ReactNode;content?:ReactNode;disabled?:boolean};
const sortableLabel=(item:SortableItem)=>item.label??(typeof item.title==="string"?item.title:String(item.title));
export function SortableList({items,onReorder,onRemove,renderActions,initialExpanded=[]}:{items:SortableItem[];onReorder:(items:SortableItem[])=>void;onRemove?:(id:string)=>void;renderActions?:(item:SortableItem)=>ReactNode;initialExpanded?:string[]}){const[expanded,setExpanded]=useState<string[]>(initialExpanded),[dragged,setDragged]=useState<string>(),[context,setContext]=useState<{id:string;x:number;y:number}|null>(null);const contextItem=items.find(item=>item.id===context?.id),contextActions:MenuAction[]=contextItem&&onRemove?[{id:"remove",label:`Remove ${sortableLabel(contextItem)}`,danger:true,onSelect:()=>onRemove(contextItem.id)}]:[];return <div className="bv-sortable-list">{items.map(item=><article key={item.id} draggable={!item.disabled} onContextMenu={event=>{if(!onRemove)return;event.preventDefault();setContext({id:item.id,x:event.clientX,y:event.clientY})}} onDragStart={()=>setDragged(item.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(!dragged||dragged===item.id)return;const next=[...items],from=next.findIndex(value=>value.id===dragged),to=next.findIndex(value=>value.id===item.id),[moved]=next.splice(from,1);next.splice(to,0,moved);onReorder(next);setDragged(undefined);}}><header><button type="button" className="bv-drag-handle" aria-label={`Reorder ${sortableLabel(item)}`}>⠿</button><div><strong>{item.title}</strong>{item.description&&<small>{item.description}</small>}</div>{renderActions?.(item)}<span className="bv-segmented-actions">{onRemove&&<Popover trigger={({open,toggle})=><Button intent="ghost" iconOnly aria-label={`Actions for ${sortableLabel(item)}`} aria-haspopup="menu" aria-expanded={open} onClick={toggle}>•••</Button>}><Menu actions={[{id:"remove",label:`Remove ${sortableLabel(item)}`,danger:true,onSelect:()=>onRemove(item.id)}]}/></Popover>}{item.content&&<Button intent="ghost" icon={<span className="bv-chevron"/>} iconOnly aria-label={`${expanded.includes(item.id)?"Collapse":"Expand"} ${sortableLabel(item)}`} aria-expanded={expanded.includes(item.id)} onClick={()=>setExpanded(current=>current.includes(item.id)?current.filter(id=>id!==item.id):[...current,item.id])}/>}</span></header>{item.summary&&<div className="bv-sortable-summary">{item.summary}</div>}{item.content&&expanded.includes(item.id)&&<div className="bv-sortable-content">{item.content}</div>}</article>)}<ContextMenu open={Boolean(context&&contextActions.length)} x={context?.x??0} y={context?.y??0} actions={contextActions} onClose={()=>setContext(null)}/></div>}
export function CompactResourceList({action,empty,children}:{action?:ReactNode;empty?:ReactNode;children?:ReactNode}){return <div className="bv-compact-resource-list">{action}{children??<p className="bv-compact-resource-empty">{empty}</p>}</div>}
export function CompactResourceGroup({control,title,meta,actions,children}:{control:ReactNode;title:ReactNode;meta?:ReactNode;actions?:ReactNode;children?:ReactNode}){return <section className="bv-compact-resource-group"><header><span className="bv-compact-resource-control">{control}</span><strong className="bv-compact-resource-title">{title}</strong>{meta&&<small>{meta}</small>}{actions&&<span className="bv-compact-resource-actions">{actions}</span>}</header>{children}</section>}
export function CompactResourceRow({control,title,values,dragHandle,actions=[]}:{control:ReactNode;title:ReactNode;values?:ReactNode;dragHandle?:ReactNode;actions?:MenuAction[]}){const[context,setContext]=useState<{x:number;y:number}|null>(null);return <div className="bv-compact-resource-row" onContextMenu={event=>{if(!actions.length)return;event.preventDefault();setContext({x:event.clientX,y:event.clientY})}}>{dragHandle}<span className="bv-compact-resource-control">{control}</span><span className="bv-compact-resource-title">{title}</span>{values&&<span className="bv-compact-resource-values">{values}</span>}{actions.length>0&&<Popover trigger={({open,toggle})=><Button density="compact" intent="ghost" iconOnly aria-label="Resource actions" aria-haspopup="menu" aria-expanded={open} onClick={toggle}>•••</Button>}><Menu actions={actions}/></Popover>}<ContextMenu open={Boolean(context)} x={context?.x??0} y={context?.y??0} actions={actions} onClose={()=>setContext(null)}/></div>}
export function CompactSortableRows<T extends StableIdItem>({items,onReorder,renderRow,label="Reorder item"}:{items:T[];onReorder:(items:T[])=>void;renderRow:(item:T,index:number,dragHandle:ReactNode)=>ReactNode;label?:string}){
    const[dragged,setDragged]=useState<string>(),gesture=useRef<{pointerId:number;sourceId:string;startX:number;startY:number;targetId?:string;placement?:"before"|"after";moved:boolean}>(),rows=useRef(new Map<string,HTMLDivElement>()),clear=()=>{gesture.current=undefined;setDragged(undefined)};
    return <div className="bv-compact-sortable-rows" onPointerMove={event=>{const active=gesture.current;if(!active||active.pointerId!==event.pointerId)return;if(Math.hypot(event.clientX-active.startX,event.clientY-active.startY)<4)return;active.moved=true;event.preventDefault();event.stopPropagation();const target=[...rows.current.entries()].find(([,node])=>{const rect=node.getBoundingClientRect();return event.clientX>=rect.left&&event.clientX<=rect.right&&event.clientY>=rect.top&&event.clientY<=rect.bottom}),targetId=target?.[0];if(!targetId||!items.some(value=>value.id===targetId)){delete active.targetId;delete active.placement;return}const rect=target[1].getBoundingClientRect();active.targetId=targetId;active.placement=event.clientY>=rect.top+rect.height/2?"after":"before"}} onPointerUp={event=>{const active=gesture.current;if(!active||active.pointerId!==event.pointerId)return;event.stopPropagation();gesture.current=undefined;const handle=event.currentTarget.querySelector<HTMLElement>(`[data-bv-drag-source="${active.sourceId}"]`);if(handle?.hasPointerCapture(event.pointerId))handle.releasePointerCapture(event.pointerId);setDragged(undefined);if(active.moved&&active.targetId&&active.placement){const next=reorderByStableId(items,active.sourceId,active.targetId,active.placement);if(next!==items)onReorder(next)}}} onPointerCancel={clear} onLostPointerCapture={()=>{if(gesture.current)clear()}} onKeyDown={event=>{if(event.key==="Escape"){event.preventDefault();clear()}}}>{items.map((item,index)=>{const handle=<button type="button" className={`bv-compact-drag-handle ${dragged===item.id?"is-dragging":""}`} data-bv-drag-source={item.id} aria-label={`${label} ${index+1}`} title="Drag to reorder" onPointerDown={event=>{if(event.button!==0)return;event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);gesture.current={pointerId:event.pointerId,sourceId:item.id,startX:event.clientX,startY:event.clientY,moved:false};setDragged(item.id)}}>⠿</button>;return <div className="bv-compact-sort-target" data-bv-sort-id={item.id} ref={node=>{if(node)rows.current.set(item.id,node);else rows.current.delete(item.id)}} key={item.id}>{renderRow(item,index,handle)}</div>})}</div>
}
export function HoverPreview({src,safe=true,label,children,delay=450}:{src?:string|null;safe?:boolean;label:string;children:ReactNode;delay?:number}){const[open,setOpen]=useState(false),[point,setPoint]=useState({x:0,y:0}),[previewSize,setPreviewSize]=useState<{width:number;height:number}>(),timer=useRef<number>();const clear=()=>{if(timer.current)window.clearTimeout(timer.current);timer.current=undefined},close=()=>{clear();setOpen(false)},schedule=(next:{x:number;y:number})=>{setPoint(next);clear();if(!safe||!src)return;timer.current=window.setTimeout(()=>setOpen(true),delay)};useEffect(()=>{if(!open)return;const dismiss=()=>setOpen(false),key=(event:KeyboardEvent)=>{if(event.key==="Escape")dismiss()};window.addEventListener("resize",dismiss);window.addEventListener("scroll",dismiss,true);document.addEventListener("keydown",key);return()=>{window.removeEventListener("resize",dismiss);window.removeEventListener("scroll",dismiss,true);document.removeEventListener("keydown",key)}},[open]);useEffect(()=>{close();setPreviewSize(undefined);return clear},[src,safe]);const size=previewSize??HOVER_PREVIEW_MAX_SIZE,placed=typeof window==="undefined"?{left:0,top:0,width:size.width,height:size.height}:placeHoverPreview(point,size,{width:window.innerWidth,height:window.innerHeight}),previewStyle={left:placed.left,top:placed.top,"--bv-hover-preview-max-width":`${placed.width}px`,"--bv-hover-preview-max-height":`${placed.height}px`}as CSSProperties;return <span className="bv-hover-preview-anchor" tabIndex={safe&&src?0:undefined} onPointerEnter={event=>schedule({x:event.clientX,y:event.clientY})} onPointerMove={event=>setPoint({x:event.clientX,y:event.clientY})} onPointerLeave={close} onFocus={event=>{const rect=event.currentTarget.getBoundingClientRect();schedule({x:rect.right,y:rect.top})}} onBlur={close}>{children}{open&&safe&&src?<Portal><span className="bv-hover-preview" style={previewStyle}><img src={src} alt={`${label} preview`} loading="eager" decoding="async" onLoad={event=>setPreviewSize(fitHoverPreviewSize({width:event.currentTarget.naturalWidth,height:event.currentTarget.naturalHeight}))}/></span></Portal>:null}</span>}
export function IncrementalResourceList<T>({items,itemKey,renderItem,empty,loading=false,loadingLabel="Loading resources…",mode="list",initialCount,step=8,label="Resources"}:{items:T[];itemKey:(item:T)=>React.Key;renderItem:(item:T,index:number)=>ReactNode;empty:ReactNode;loading?:boolean;loadingLabel?:string;mode?:"list"|"grid";initialCount?:number;step?:number;label?:string}){const initial=initialCount??(mode==="grid"?8:12),[limit,setLimit]=useState(initial);useEffect(()=>setLimit(initial),[items,mode,initial]);const mounted=items.slice(0,limit),more=mounted.length<items.length,load=()=>setLimit(current=>Math.min(items.length,current+step));return <section className="bv-incremental-resource-list" aria-label={label} aria-busy={loading}><div className={`bv-resource-${mode}`} onScroll={event=>{const element=event.currentTarget;if(more&&element.scrollTop+element.clientHeight>=element.scrollHeight-80)load()}}>{mounted.map((item,index)=><React.Fragment key={itemKey(item)}>{renderItem(item,index)}</React.Fragment>)}{items.length===0&&<div className="bv-incremental-empty">{loading?<div className="bv-resource-loading"><span aria-hidden="true"/><strong>{loadingLabel}</strong></div>:empty}</div>}</div><footer><span>{loading&&items.length===0?loadingLabel:items.length===0?"0 results":`${mounted.length} of ${items.length}`}</span>{more&&<Button density="compact" intent="ghost" onClick={load}>Load {Math.min(step,items.length-mounted.length)} more</Button>}</footer></section>}
export type ImageOption={id:string;name:string;meta?:string;src?:string;thumbnail?:string;disabled?:boolean};
export type ImagePreviewView={scale:number;x:number;y:number};
export function ImagePreview({open,src,title,meta,onClose}:{open:boolean;src?:string;title:string;meta?:string;onClose:()=>void}){
    const[size,setSize]=useState<{width:number;height:number}>(),[view,setView]=useState<ImagePreviewView>({scale:1,x:0,y:0}),[dragging,setDragging]=useState(false);
    const stage=useRef<HTMLDivElement>(null),image=useRef<HTMLImageElement>(null),drag=useRef<{pointerId:number;x:number;y:number}>();
    const clampView=(candidate:ImagePreviewView):ImagePreviewView=>{const scale=Math.max(.25,Math.min(8,candidate.scale));if(scale<=1||!stage.current||!image.current)return{scale,x:0,y:0};const maxX=Math.max(0,(image.current.clientWidth*scale-stage.current.clientWidth+36)/2),maxY=Math.max(0,(image.current.clientHeight*scale-stage.current.clientHeight+36)/2);return{scale,x:Math.max(-maxX,Math.min(maxX,candidate.x)),y:Math.max(-maxY,Math.min(maxY,candidate.y))}};
    const zoom=(next:number,origin={x:0,y:0})=>setView(current=>{const scale=Math.max(.25,Math.min(8,next));if(scale===current.scale)return current;const ratio=scale/current.scale;return clampView({scale,x:origin.x-(origin.x-current.x)*ratio,y:origin.y-(origin.y-current.y)*ratio})});
    const fit=()=>setView({scale:1,x:0,y:0});
    useEffect(()=>{if(!open)return;setSize(undefined);setView({scale:1,x:0,y:0});const key=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose();else if(event.key==="0")setView({scale:1,x:0,y:0});else if(event.key==="+"||event.key==="=")setView(current=>{const scale=Math.min(8,current.scale*1.25),ratio=scale/current.scale;return clampView({scale,x:current.x*ratio,y:current.y*ratio})});else if(event.key==="-")setView(current=>{const scale=Math.max(.25,current.scale/1.25),ratio=scale/current.scale;return clampView({scale,x:current.x*ratio,y:current.y*ratio})})};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[open,src,onClose]);
    if(!open)return null;
    return <Portal><div className="bv-image-preview" onPointerDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="bv-image-preview-dialog" role="dialog" aria-modal="true" aria-label={`${title} preview`}><header><span className="bv-image-preview-icon" aria-hidden="true"><svg viewBox="0 0 20 20"><rect x="3" y="4" width="14" height="12" rx="1.5"/><circle cx="13.5" cy="7.5" r="1.25"/><path d="m5 13 3-3 2.4 2.1 1.8-1.5L15 13"/></svg></span><div><h2>{title}</h2>{meta&&<small>{meta}</small>}</div><Button type="button" intent="ghost" icon="×" iconOnly aria-label="Close preview" onClick={onClose}/></header><div ref={stage} className={`bv-image-preview-stage ${view.scale>1?"is-pannable":""} ${dragging?"is-dragging":""}`} onWheel={event=>{event.preventDefault();const rect=event.currentTarget.getBoundingClientRect();zoom(view.scale*(event.deltaY<0?1.15:1/1.15),{x:event.clientX-rect.left-rect.width/2,y:event.clientY-rect.top-rect.height/2})}} onDoubleClick={()=>view.scale===1?zoom(2):fit()} onPointerDown={event=>{if(view.scale<=1)return;event.currentTarget.setPointerCapture(event.pointerId);drag.current={pointerId:event.pointerId,x:event.clientX,y:event.clientY};setDragging(true)}} onPointerMove={event=>{if(!drag.current||drag.current.pointerId!==event.pointerId)return;const dx=event.clientX-drag.current.x,dy=event.clientY-drag.current.y;drag.current={pointerId:event.pointerId,x:event.clientX,y:event.clientY};setView(current=>clampView({...current,x:current.x+dx,y:current.y+dy}))}} onPointerUp={event=>{if(drag.current?.pointerId!==event.pointerId)return;event.currentTarget.releasePointerCapture(event.pointerId);drag.current=undefined;setDragging(false)}} onPointerCancel={()=>{drag.current=undefined;setDragging(false)}}>{src?<img ref={image} src={src} alt={title} draggable={false} style={{transform:`translate3d(${view.x}px,${view.y}px,0) scale(${view.scale})`}} onLoad={event=>{setSize({width:event.currentTarget.naturalWidth,height:event.currentTarget.naturalHeight});fit()}}/>:<span>No image available</span>}</div><footer><span>{size?`${size.width} × ${size.height} px`:"Loading image…"}</span><span className="bv-image-preview-help">Wheel to zoom · drag to pan · double-click to toggle</span><div className="bv-image-preview-controls"><Button type="button" intent="ghost" icon="−" iconOnly aria-label="Zoom out" disabled={view.scale<=.25} onClick={()=>zoom(view.scale/1.25)}/><output aria-live="polite">{Math.round(view.scale*100)}%</output><Button type="button" intent="ghost" icon="+" iconOnly aria-label="Zoom in" disabled={view.scale>=8} onClick={()=>zoom(view.scale*1.25)}/><Button type="button" intent="ghost" aria-label="Fit image to window" onClick={fit}>Fit</Button></div></footer></section></div></Portal>
}
export const imageOptionSource=(item?:ImageOption)=>item?.thumbnail?.trim()||item?.src?.trim()||undefined;
export const imageOptionPreviewSource=(item?:ImageOption)=>item?.src?.trim()||undefined;
const imageOptionVisual=(item?:ImageOption)=>{const src=imageOptionSource(item);return src?<img src={src} alt=""/>:<span className="bv-image-picker-placeholder" aria-hidden="true"><svg viewBox="0 0 20 20"><rect x="3" y="4" width="14" height="12" rx="1.5"/><path d="m5 13 3-3 2.4 2.1 1.8-1.5L15 13"/></svg></span>};
export function ImagePickerOptionRow({item,selected=false,disabled=false,onSelect}:{item:ImageOption;selected?:boolean;disabled?:boolean;onSelect:(id:string)=>void}){
    const unavailable=disabled||Boolean(item.disabled);
    return <button type="button" role="option" aria-selected={selected} disabled={unavailable} onClick={()=>{if(!unavailable)onSelect(item.id)}}>{imageOptionVisual(item)}<span><strong>{item.name}</strong>{item.meta&&<small>{item.meta}</small>}</span></button>;
}
export function ImagePickerOptions({label,options,value,disabled=false,onSelect}:{label:string;options:ImageOption[];value:string;disabled?:boolean;onSelect:(id:string)=>void}){
    return <div role="listbox" aria-label={label}>{options.map(item=><ImagePickerOptionRow item={item} selected={item.id===value} disabled={disabled} onSelect={onSelect} key={item.id}/>)}</div>;
}
export function ImagePicker({label,options,value,onValue,largePreview=true,labelVisible=true,className,disabled=false}:{label:string;options:ImageOption[];value:string;onValue:(id:string)=>void;largePreview?:boolean;labelVisible?:boolean;className?:string;disabled?:boolean}){
    const[open,setOpen]=useState(false),[preview,setPreview]=useState(false),anchor=useRef<HTMLDivElement>(null),selected=options.find(item=>item.id===value),selectedPreview=imageOptionPreviewSource(selected);
    const toggle=()=>{if(!disabled)setOpen(current=>!current)};
    return <div ref={anchor} className={["bv-image-picker",className].filter(Boolean).join(" ")}>
        {labelVisible&&<span className="bv-control-label">{label}</span>}
        <div className="bv-image-picker-control"><button type="button" className="bv-image-picker-trigger" aria-label={label} aria-haspopup="listbox" aria-expanded={open} disabled={disabled} onClick={toggle}>{imageOptionVisual(selected)}<span><strong>{selected?.name??"No selection"}</strong>{selected?.meta&&<small>{selected.meta}</small>}</span></button>
        {largePreview&&<Button type="button" intent="ghost" className="bv-image-preview-action" iconOnly disabled={disabled||!selectedPreview} aria-label={`Open large preview for ${selected?.name??label}`} title="Open large preview" onClick={()=>setPreview(true)}><svg viewBox="0 0 20 20" aria-hidden="true"><rect x="3" y="4" width="14" height="12" rx="1.5"/><circle cx="13.5" cy="7.5" r="1.25"/><path d="m5 13 3-3 2.4 2.1 1.8-1.5L15 13"/></svg></Button>}
        <Button type="button" intent="ghost" className="bv-image-picker-toggle" icon={<span className="bv-chevron"/>} iconOnly disabled={disabled} aria-label={`Choose ${label}`} aria-haspopup="listbox" aria-expanded={open} onClick={toggle}/></div>
        <AnchoredPopover open={open} anchor={anchor} onClose={()=>setOpen(false)} className="bv-image-picker-menu" matchWidth><ImagePickerOptions label={label} options={options} value={value} disabled={disabled} onSelect={id=>{onValue(id);setOpen(false)}}/></AnchoredPopover>
        <ImagePreview open={preview} src={selectedPreview} title={selected?.name??label} meta={selected?.meta} onClose={()=>setPreview(false)}/>
    </div>
}export type TreeNode={id:string;label:ReactNode;meta?:ReactNode;icon?:ReactNode;children?:TreeNode[];actions?:ReactNode;disabled?:boolean};
export function Tree({nodes,selected,onSelect,onMove,expanded,onExpanded,label="Items"}:{nodes:TreeNode[];selected:string[];onSelect:(id:string,event:React.MouseEvent)=>void;onMove?:(source:string,target:string)=>void;expanded:string[];onExpanded:(ids:string[])=>void;label?:string}){const render=(node:TreeNode,level:number)=><div key={node.id} role="treeitem" aria-level={level} aria-selected={selected.includes(node.id)} aria-expanded={node.children?.length?expanded.includes(node.id):undefined} draggable={Boolean(onMove)} onDragStart={e=>e.dataTransfer.setData("text/bv-tree-id",node.id)} onDragOver={e=>onMove&&e.preventDefault()} onDrop={e=>{e.preventDefault();onMove?.(e.dataTransfer.getData("text/bv-tree-id"),node.id)}}><div className="bv-tree-row" onClick={event=>onSelect(node.id,event)}>{node.children?.length?<button type="button" className="bv-tree-expander" onClick={e=>{e.stopPropagation();onExpanded(expanded.includes(node.id)?expanded.filter(id=>id!==node.id):[...expanded,node.id])}}><span className="bv-chevron"/></button>:<span/>}{node.icon}<span className="bv-tree-label">{node.label}</span>{node.meta&&<span className="bv-tree-meta">{node.meta}</span>}{node.actions&&<span className="bv-tree-actions">{node.actions}</span>}</div>{node.children&&expanded.includes(node.id)&&<div role="group">{node.children.map(child=>render(child,level+1))}</div>}</div>;return <div className="bv-tree" role="tree" aria-label={label}>{nodes.map(node=>render(node,1))}</div>}

export const TreeButton=React.forwardRef<HTMLButtonElement,React.ButtonHTMLAttributes<HTMLButtonElement>>(function TreeButton({type="button",...props},ref){return <button {...props} type={type} ref={ref}/>});
export const InlineTextEdit=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(function InlineTextEdit(props,ref){return <input {...props} ref={ref}/>});
export function TreeOverflowMenu({label="Actions",actions}:{label?:string;actions:Array<{label:string;danger?:boolean;disabled?:boolean;run:()=>void}>}){return <details className="layer-overflow" onClick={event=>event.stopPropagation()}><summary title={label} aria-label={label}>•••</summary><div>{actions.map(action=><button type="button" key={action.label} className={action.danger?"danger":""} disabled={action.disabled} onClick={event=>{event.currentTarget.closest("details")?.removeAttribute("open");action.run()}}>{action.label}</button>)}</div></details>}
