import React,{ReactNode,useCallback,useEffect,useRef}from"react";
import{Button}from"./actions";
export type Tone="neutral"|"info"|"success"|"warning"|"danger";
export function Callout({tone="neutral",title,children,icon,actions,onClose}:{tone?:Tone;title?:ReactNode;children:ReactNode;icon?:ReactNode;actions?:ReactNode;onClose?:()=>void}){return <aside className={`bv-callout ${tone}`} role={tone==="danger"?"alert":"status"}>{icon&&<span className="bv-callout-icon">{icon}</span>}<div>{title&&<strong>{title}</strong>}<div>{children}</div>{actions&&<div className="bv-callout-actions">{actions}</div>}</div>{onClose&&<Button intent="ghost" iconOnly aria-label="Close" onClick={onClose}>×</Button>}</aside>}
export function Badge({children,tone="neutral",dot=false}:{children?:ReactNode;tone?:Tone;dot?:boolean}){return <span className={`bv-badge ${tone} ${dot?"dot":""}`}>{children}</span>}
export function Progress({value,label,indeterminate=false}:{value?:number;label?:ReactNode;indeterminate?:boolean}){return <div className={`bv-progress ${indeterminate?"indeterminate":""}`}>{label&&<div><span>{label}</span>{!indeterminate&&<output>{Math.round((value??0)*100)}%</output>}</div>}<div role="progressbar" aria-valuenow={indeterminate?undefined:Math.round((value??0)*100)}><span style={{width:indeterminate?undefined:`${(value??0)*100}%`}}/></div></div>}
export function Skeleton({lines=3}:{lines?:number}){return <div className="bv-skeleton" aria-hidden="true">{Array.from({length:lines},(_,i)=><span key={i}/>)}</div>}
export function EmptyState({icon,title,description,actions}:{icon?:ReactNode;title:string;description?:ReactNode;actions?:ReactNode}){return <div className="bv-empty-state">{icon}<strong>{title}</strong>{description&&<p>{description}</p>}{actions}</div>}
export function Toast({tone="neutral",title,children,onClose,duration=0}:{tone?:Tone;title:string;children?:ReactNode;onClose:()=>void;duration?:number}){const timer=useRef<number>();const stop=useCallback(()=>{if(timer.current)window.clearTimeout(timer.current)},[]),start=useCallback(()=>{stop();if(duration)timer.current=window.setTimeout(onClose,duration)},[duration,onClose,stop]);useEffect(()=>{start();return stop},[start,stop]);return <div className={`bv-toast ${tone}`} role="status" tabIndex={0} onPointerEnter={stop} onPointerLeave={start} onFocus={stop} onBlur={start}><div><strong>{title}</strong>{children&&<p>{children}</p>}</div><Button intent="ghost" iconOnly aria-label="Dismiss" onClick={onClose}>×</Button></div>}
export function ToastStack({children}:{children:ReactNode}){return <div className="bv-toast-stack" aria-live="polite">{children}</div>}
export function ValidationSummary({title,issues}:{title:string;issues:Array<{id?:string;message:string}>}){return <Callout tone={issues.length?"danger":"success"} title={title}>{issues.length?<ul>{issues.map((issue,i)=><li key={i}>{issue.id?<a href={`#${issue.id}`}>{issue.message}</a>:issue.message}</li>)}</ul>:<p>All values are valid.</p>}</Callout>}
