import React, { ChangeEvent, forwardRef, KeyboardEvent, ReactNode, useEffect, useId, useMemo, useRef, useState } from "react";
import { HexAlphaColorPicker, HexColorPicker } from "react-colorful";
import EditorModule from "react-simple-code-editor";
import Prism from "prismjs";
import "prismjs/components/prism-json";
import { Button } from "./actions";
import { AdaptiveFieldPopover, AnchoredPopover } from "./overlays";
const CodeEditor=EditorModule;

export type FieldStatus = "default" | "error" | "success" | "warning";
export type FieldFrameProps = { label:string; help?:ReactNode; error?:ReactNode; required?:boolean; icon?:ReactNode; className?:string; children:ReactNode };

export function FieldGrid({children,minimum=165,className=""}:{children:ReactNode;minimum?:number;className?:string}) {
    return <div className={`bv-field-grid ${className}`.trim()} style={{"--bv-field-grid-min":`${minimum}px`} as React.CSSProperties}>{children}</div>;
}

export function ChoiceGrid({children,minimum=145,className=""}:{children:ReactNode;minimum?:number;className?:string}) {
    return <div className={`bv-choice-grid ${className}`.trim()} style={{"--bv-choice-grid-min":`${minimum}px`} as React.CSSProperties}>{children}</div>;
}

export function FieldFrame({ label, help, error, required, icon, className="", children }:FieldFrameProps) {
    return <label className={`bv-control-field ${error ? "is-error" : ""} ${className}`.trim()}><span className="bv-control-label">{icon && <span className="bv-field-icon">{icon}</span>}<span>{label}</span>{required && <span aria-hidden="true"> *</span>}</span>{children}{error ? <small className="bv-control-message is-error">{error}</small> : help && <small className="bv-control-help bv-control-help-overlay">{help}</small>}</label>;
}

export type TextFieldProps = Omit<React.InputHTMLAttributes<HTMLInputElement>,"onChange"> & { label:string; help?:ReactNode; error?:ReactNode; icon?:ReactNode; suffix?:ReactNode; onValue?:(value:string)=>void };
export function TextField({ label,help,error,icon,suffix,onValue,className="",...input }:TextFieldProps) {
    const shell=(expanded=false)=><span className="bv-input-shell">{icon&&<span className="bv-field-icon" aria-hidden="true">{icon}</span>}<input {...input} id={expanded&&input.id?`${input.id}-expanded`:input.id} aria-label={expanded?label:input["aria-label"]} aria-invalid={Boolean(error)} onChange={event=>onValue?.(event.target.value)}/>{suffix&&<span className="bv-field-suffix">{suffix}</span>}</span>;
    return <FieldFrame label={label} help={help} error={error} className={className}><AdaptiveFieldPopover label={label} summary={String(input.value??input.defaultValue??input.placeholder??"Edit value")} icon={icon} popover={shell(true)}>{shell()}</AdaptiveFieldPopover></FieldFrame>;
}
export type TextareaFieldProps = Omit<React.TextareaHTMLAttributes<HTMLTextAreaElement>,"onChange"> & { label:string; help?:ReactNode; error?:ReactNode; icon?:ReactNode; resize?:"none"|"vertical"|"both"; onValue?:(value:string)=>void };
export function TextareaField({ label,help,error,icon,resize="vertical",onValue,className="",...textarea }:TextareaFieldProps) {
    const shell=(expanded=false)=><span className={`bv-textarea-shell resize-${resize}`}>{icon&&<span className="bv-field-icon" aria-hidden="true">{icon}</span>}<textarea {...textarea} id={expanded&&textarea.id?`${textarea.id}-expanded`:textarea.id} aria-label={expanded?label:textarea["aria-label"]} aria-invalid={Boolean(error)} onChange={event=>onValue?.(event.target.value)}/></span>;
    const summary=String(textarea.value??textarea.defaultValue??textarea.placeholder??"Edit text");
    return <FieldFrame label={label} help={help} error={error} className={`bv-textarea-field ${className}`}><AdaptiveFieldPopover label={label} summary={summary} icon={icon} popover={shell(true)}>{shell()}</AdaptiveFieldPopover></FieldFrame>;
}export const TextareaControl=forwardRef<HTMLTextAreaElement,React.TextareaHTMLAttributes<HTMLTextAreaElement>>(function TextareaControl(props,ref){return <textarea {...props} ref={ref}/>});

export type NumberFieldProps = { label:string; value:number; min:number; max:number; step:number; unit?:string; icon?:ReactNode; help?:ReactNode; slider?:boolean; onValue:(value:number)=>void; className?:string };
export function NumberField({ label,value,min,max,step,unit,icon,help,slider=true,onValue,className="" }:NumberFieldProps) {
    const id=useId(), [draft,setDraft]=useState(String(value));
    useEffect(()=>setDraft(String(value)),[value]);
    const clamp=(next:number)=>Math.max(min,Math.min(max,next)),commit=()=>{const next=Number(draft);Number.isFinite(next)?onValue(clamp(next)):setDraft(String(value));},fill=`${Math.max(0,Math.min(100,(value-min)/Math.max(Number.EPSILON,max-min)*100))}%`;
    const box=(inputId:string)=><div className="bv-number-box">{icon&&<span className="bv-field-icon" aria-hidden="true">{icon}</span>}<input id={inputId} value={draft} inputMode={Number.isInteger(step)?"numeric":"decimal"} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur();if(e.key==="Escape")setDraft(String(value));}}/>{unit&&<span className="bv-number-unit">{unit}</span>}</div>;
    const range=<div className="bv-number-slider" style={{"--bubble-left":fill} as React.CSSProperties}><output>{value}{unit??""}</output><input className="bv-number-track" type="range" min={min} max={max} step={step} value={value} style={{"--range-fill":fill} as React.CSSProperties} aria-labelledby={`${id}-label`} onChange={e=>onValue(clamp(+e.target.value))}/></div>,ticks=<div className="bv-number-ticks"><span>{min}</span><span>{max}</span></div>;
    const inline=<>{<div className="bv-number-value-row">{slider&&range}{box(id)}</div>}{slider&&ticks}</>;
    const expanded=<div className="bv-number-popup">{slider&&range}{box(`${id}-expanded`)}{slider&&ticks}</div>;
    return <div className={`bv-number-field ${slider?"has-slider":"direct-only"} ${className}`.trim()}><label id={`${id}-label`} htmlFor={id}>{label}</label><AdaptiveFieldPopover label={label} summary={`${value}${unit??""}`} icon={icon} popover={expanded}>{inline}</AdaptiveFieldPopover>{help&&<small className="bv-control-help bv-control-help-overlay">{help}</small>}</div>;
}
export type SelectOption={ value:string; label:string; description?:string; icon?:ReactNode; meta?:ReactNode; disabled?:boolean };
export type SelectValueMeta = { shiftKey:boolean };
function SelectControl({label,value,options,onValue,disabled,className=""}:{label:string;value:string;options:SelectOption[];onValue:(value:string,meta:SelectValueMeta)=>void;disabled?:boolean;className?:string}) {
    const [open,setOpen]=useState(false), anchor=useRef<HTMLDivElement>(null), selected=options.find(option=>option.value===value);
    return <div ref={anchor} className={`bv-select-popover ${className}`.trim()}><button type="button" className="bv-select-trigger" disabled={disabled} aria-label={label} aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(current=>!current)}><span>{selected?.label??"Select…"}</span><span className="bv-chevron" aria-hidden="true"/></button><AnchoredPopover open={open} anchor={anchor} onClose={()=>setOpen(false)} className="bv-select-menu" matchWidth><div role="listbox" aria-label={label}>{options.map(option=><button type="button" role="option" aria-selected={option.value===value} disabled={option.disabled} key={option.value} onClick={event=>{onValue(option.value,{shiftKey:event.shiftKey});setOpen(false)}}>{option.icon}<span>{option.label}</span></button>)}</div></AnchoredPopover></div>;
}export function SelectField({label,value,options,onValue,help,disabled}:{label:string;value:string;options:SelectOption[];onValue:(value:string)=>void;help?:ReactNode;disabled?:boolean}) {
    return <FieldFrame label={label} help={help}><SelectControl label={label} value={value} options={options} onValue={onValue} disabled={disabled}/></FieldFrame>;
}
export function CompactSelect({label,value,options,onValue,disabled,className=""}:{label:string;value:string;options:SelectOption[];onValue:(value:string,meta:SelectValueMeta)=>void;disabled?:boolean;className?:string}){return <SelectControl label={label} value={value} options={options} onValue={onValue} disabled={disabled} className={`bv-density-compact ${className}`}/>}
export function RichSelect({label,value,options,onValue,help}:{label:string;value:string;options:SelectOption[];onValue:(value:string)=>void;help?:ReactNode}) {
    const [open,setOpen]=useState(false), anchor=useRef<HTMLDivElement>(null), selected=options.find(option=>option.value===value);
    return <FieldFrame label={label} help={help}><div ref={anchor} className="bv-rich-select"><button type="button" className="bv-rich-select-trigger" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(!open)}>{selected?.icon}<span><strong>{selected?.label??"Select…"}</strong>{selected?.description&&<small>{selected.description}</small>}</span><span className="bv-chevron"/></button><AnchoredPopover open={open} anchor={anchor} onClose={()=>setOpen(false)} className="bv-rich-select-menu" matchWidth><div role="listbox">{options.map(option=><button type="button" role="option" aria-selected={option.value===value} disabled={option.disabled} key={option.value} onClick={()=>{onValue(option.value);setOpen(false);}}>{option.icon}<span><strong>{option.label}</strong>{option.description&&<small>{option.description}</small>}</span>{option.meta}</button>)}</div></AnchoredPopover></div></FieldFrame>;
}
export function CheckboxField({label,checked,onValue,help,disabled}:{label:string;checked:boolean;onValue:(value:boolean)=>void;help?:ReactNode;disabled?:boolean}) { return <label className="bv-checkbox-field"><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onValue(e.target.checked)}/><span className="bv-checkbox-mark" aria-hidden="true"/><span><strong>{label}</strong>{help&&<small>{help}</small>}</span></label>; }
export function ToggleField({label,value,onValue,trueLabel="True",falseLabel="False",help}:{label:string;value:boolean;onValue:(value:boolean)=>void;trueLabel?:string;falseLabel?:string;help?:ReactNode}) { return <FieldFrame label={label} help={help}><button type="button" role="switch" aria-checked={value} className="bv-toggle" onClick={()=>onValue(!value)}><span className="bv-toggle-track"><span/></span><strong>{value?trueLabel:falseLabel}</strong></button></FieldFrame>; }
export function BooleanField({variant="toggle",...props}:{variant?:"toggle"|"checkbox"|"select";label:string;value:boolean;onValue:(value:boolean)=>void;trueLabel?:string;falseLabel?:string;help?:ReactNode}) { if(variant==="checkbox")return <CheckboxField label={props.label} checked={props.value} onValue={props.onValue} help={props.help}/>;if(variant==="select")return <SelectField label={props.label} value={String(props.value)} onValue={v=>props.onValue(v==="true")} help={props.help} options={[{value:"true",label:props.trueLabel??"True"},{value:"false",label:props.falseLabel??"False"}]}/>;return <ToggleField {...props}/>; }

export function OptionSet({label,value,options,onValue,variant="radio"}:{label:string;value:string;options:SelectOption[];onValue:(value:string)=>void;variant?:"radio"|"segmented"|"select"}) { if(variant==="select")return <SelectField label={label} value={value} options={options} onValue={onValue}/>;return <FieldFrame label={label}><div className={`bv-option-set ${variant}`} role="radiogroup">{options.map(option=><button type="button" role="radio" aria-checked={option.value===value} key={option.value} onClick={()=>onValue(option.value)}>{option.icon}{option.label}</button>)}</div></FieldFrame>; }

export function TagInput({label,value,onValue,suggestions=[],placeholder}:{label:string;value:string[];onValue:(tags:string[])=>void;suggestions?:string[];placeholder?:string}) { const [draft,setDraft]=useState("");const add=()=>{const tag=draft.trim().replace(/,$/,"");if(tag&&!value.some(item=>item.toLowerCase()===tag.toLowerCase()))onValue([...value,tag]);setDraft("");};return <FieldFrame label={label}><div className="bv-tag-input"><div className="bv-tag-values">{value.map(tag=><span className="bv-tag" key={tag}>{tag}<button type="button" aria-label={`Remove ${tag}`} onClick={()=>onValue(value.filter(item=>item!==tag))}>×</button></span>)}</div><input value={draft} placeholder={placeholder} list={suggestions.length?`${label}-suggestions`:undefined} onChange={e=>setDraft(e.target.value)} onBlur={add} onKeyDown={e=>{if(e.key==="Enter"||e.key===","){e.preventDefault();add();}else if(e.key==="Backspace"&&!draft&&value.length)onValue(value.slice(0,-1));}}/>{suggestions.length>0&&<datalist id={`${label}-suggestions`}>{suggestions.map(item=><option value={item} key={item}/>)}</datalist>}</div></FieldFrame>; }

export function MultiSelect({label,value,options,onValue,searchable=false}:{label:string;value:string[];options:SelectOption[];onValue:(value:string[])=>void;searchable?:boolean}) { const [query,setQuery]=useState("");const visible=options.filter(option=>!query||option.label.toLowerCase().includes(query.toLowerCase()));return <FieldFrame label={label}><div className="bv-multi-select"><div className="bv-tag-values">{value.map(id=>{const option=options.find(item=>item.value===id);return <span className="bv-tag" key={id}>{option?.label??id}<button type="button" onClick={()=>onValue(value.filter(item=>item!==id))}>×</button></span>;})}</div>{searchable&&<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search…"/>}<div className="bv-multi-options">{visible.map(option=><CheckboxField key={option.value} label={option.label} checked={value.includes(option.value)} onValue={checked=>onValue(checked?[...value,option.value]:value.filter(item=>item!==option.value))}/>)}</div></div></FieldFrame>; }

export function TagSelect({label,value,options,onValue,minSelected=0,help}:{label:string;value:string[];options:SelectOption[];onValue:(value:string[])=>void;minSelected?:number;help?:ReactNode}) {
    const [open,setOpen]=useState(false),anchor=useRef<HTMLDivElement>(null);
    const toggle=(id:string)=>{const selected=value.includes(id);if(selected&&value.length<=minSelected)return;onValue(selected?value.filter(item=>item!==id):[...value,id]);};
    return <FieldFrame label={label} help={help}><div ref={anchor} className="bv-tag-select"><button type="button" className="bv-tag-select-trigger" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(current=>!current)}><span className="bv-tag-values">{value.map(id=><span className="bv-tag" key={id}>{options.find(item=>item.value===id)?.label??id}</span>)}</span><span className="bv-chevron" aria-hidden="true"/></button><AnchoredPopover open={open} anchor={anchor} onClose={()=>setOpen(false)} className="bv-select-menu bv-tag-select-menu" matchWidth><div role="listbox" aria-label={label} aria-multiselectable="true">{options.map(option=>{const selected=value.includes(option.value),locked=selected&&value.length<=minSelected;return <button type="button" role="option" aria-selected={selected} disabled={option.disabled||locked} key={option.value} onClick={()=>toggle(option.value)}><span className="bv-tag-select-check" aria-hidden="true">{selected?"✓":""}</span><span>{option.label}</span></button>})}</div></AnchoredPopover></div></FieldFrame>;
}

export function SearchField({label,value,onValue,options,onSelect,mode="contains"}:{label:string;value:string;onValue:(value:string)=>void;options:SelectOption[];onSelect:(option:SelectOption)=>void;mode?:"contains"|"prefix"|"fuzzy"}) { const anchor=useRef<HTMLDivElement>(null),normalized=value.toLowerCase(),score=(label:string)=>{const text=label.toLowerCase();if(mode==="prefix")return text.startsWith(normalized);if(mode==="contains")return text.includes(normalized);let i=0;for(const char of text)if(char===normalized[i])i++;return i===normalized.length;},results=value?options.filter(option=>score(option.label)):[];return <FieldFrame label={label}><div ref={anchor} className="bv-search-field"><span className="bv-input-shell"><span aria-hidden="true">⌕</span><input value={value} onChange={e=>onValue(e.target.value)} /></span><AnchoredPopover open={results.length>0} anchor={anchor} className="bv-search-results" matchWidth><div role="listbox">{results.map(option=><button type="button" role="option" key={option.value} onClick={()=>onSelect(option)}>{option.icon}<span><strong>{option.label}</strong>{option.description&&<small>{option.description}</small>}</span></button>)}</div></AnchoredPopover></div></FieldFrame>; }
export function SecretField({label,value,onValue,onClear}:{label:string;value:string;onValue:(value:string)=>void;onClear?:()=>void}) { const [visible,setVisible]=useState(false);return <FieldFrame label={label}><span className="bv-input-shell"><input type={visible?"text":"password"} value={value} autoComplete="off" onChange={e=>onValue(e.target.value)}/><Button type="button" intent="ghost" className="bv-field-action" onClick={()=>setVisible(!visible)}>{visible?"Hide":"Show"}</Button><Button type="button" intent="ghost" className="bv-field-action" onClick={()=>{onValue("");onClear?.();}}>Clear</Button></span></FieldFrame>; }

export function NativePickerField({label,value,onValue,kind="file",readOnly=false,accept}:{label:string;value:string;onValue:(value:string,files:FileList)=>void;kind?:"file"|"directory";readOnly?:boolean;accept?:string}) { const picker=useRef<HTMLInputElement>(null);const change=(e:ChangeEvent<HTMLInputElement>)=>{const files=e.target.files;if(!files?.length)return;const first=files[0], next=kind==="directory"?(first.webkitRelativePath?.split("/")[0]||first.name):first.name;onValue(next,files);};return <FieldFrame label={label}><span className="bv-input-shell"><input value={value} readOnly={readOnly} onChange={e=>onValue(e.target.value,{} as FileList)}/><Button type="button" intent="ghost" className="bv-field-action" onClick={()=>picker.current?.click()}>Browse</Button><input ref={picker} hidden type="file" accept={accept} {...(kind==="directory"?{webkitdirectory:"",directory:""} as React.InputHTMLAttributes<HTMLInputElement>:{})} onChange={change}/></span></FieldFrame>; }

export function ColorField({label,value,onValue,alpha=false,help}:{label:string;value:string;onValue:(value:string)=>void;alpha?:boolean;help?:ReactNode}) { const [open,setOpen]=useState(false),anchor=useRef<HTMLDivElement>(null),valid=/^#[0-9a-f]{6}([0-9a-f]{2})?$/i.test(value),Picker=alpha?HexAlphaColorPicker:HexColorPicker,input=<input value={value} aria-label={`${label} hexadecimal value`} spellCheck={false} onChange={e=>onValue(e.target.value)}/>,picker=<div className="bv-color-expanded">{input}<Picker color={valid?value:(alpha?"#8D70FFFF":"#8D70FF")} onChange={onValue}/></div>;return <FieldFrame label={label} help={help} error={valid?undefined:"Enter a valid hexadecimal color."}><AdaptiveFieldPopover label={label} summary={value} icon={<span className="bv-color-dot" style={{background:valid?value:"#000"}}/>} popover={picker}><div ref={anchor} className="bv-color-field"><button type="button" className="bv-color-swatch" style={{background:valid?value:"#000"}} onClick={()=>setOpen(!open)} aria-label={`${label}: ${value}`} aria-haspopup="dialog" aria-expanded={open}/>{input}<AnchoredPopover open={open} anchor={anchor} onClose={()=>setOpen(false)} className="bv-color-popover">{picker}</AnchoredPopover></div></AdaptiveFieldPopover></FieldFrame>; }
export type Keybinding={key:string;ctrl?:boolean;alt?:boolean;shift?:boolean;meta?:boolean};
export function KeybindingField({label,value,onValue,reserved=[]}:{label:string;value?:Keybinding;onValue:(value?:Keybinding)=>void;reserved?:string[]}) { const [recording,setRecording]=useState(false);const text=value?[value.ctrl&&"Ctrl",value.alt&&"Alt",value.shift&&"Shift",value.meta&&"Meta",value.key].filter(Boolean).join(" + "):"Unassigned";const keyDown=(e:KeyboardEvent<HTMLButtonElement>)=>{if(!recording)return;e.preventDefault();if(e.key==="Escape"){setRecording(false);return;}if(["Control","Shift","Alt","Meta"].includes(e.key))return;onValue({key:e.key.length===1?e.key.toUpperCase():e.key,ctrl:e.ctrlKey,alt:e.altKey,shift:e.shiftKey,meta:e.metaKey});setRecording(false);};return <FieldFrame label={label} error={reserved.includes(text.split(" + ").join("+"))?"This shortcut is reserved.":undefined}><div className="bv-keybinding"><Button type="button" intent="secondary" onKeyDown={keyDown} onClick={()=>setRecording(true)}>{recording?"Press shortcut…":text}</Button><Button type="button" intent="secondary" onClick={()=>setRecording(true)}>Record</Button><Button type="button" intent="ghost" onClick={()=>onValue(undefined)}>Clear</Button></div></FieldFrame>; }

export function JsonEditor({label,value,onValue,help,minHeight=180}:{label:string;value:string;onValue:(value:string)=>void;help?:ReactNode;minHeight?:number}) { let error="";try{JSON.parse(value)}catch(reason){error=reason instanceof Error?reason.message:String(reason)}return <FieldFrame label={label} help={help} error={error||undefined}><div className="bv-json-editor"><div className="bv-json-toolbar"><Button type="button" intent="ghost" disabled={Boolean(error)} onClick={()=>{try{onValue(JSON.stringify(JSON.parse(value),null,2))}catch{}}}>Format</Button></div><CodeEditor value={value} onValueChange={onValue} highlight={(code:string)=>Prism.highlight(code,Prism.languages.json,"json")} padding={12} tabSize={2} insertSpaces style={{minHeight}}/></div></FieldFrame>; }

export function CoordinateField({label,value,onValue,unit="px"}:{label:string;value:{x:number;y:number};onValue:(value:{x:number;y:number})=>void;unit?:string}) { return <fieldset className="bv-compound-field"><legend>{label}</legend><NumberField label="X" value={value.x} min={-999999} max={999999} step={1} unit={unit} slider={false} onValue={x=>onValue({...value,x})}/><NumberField label="Y" value={value.y} min={-999999} max={999999} step={1} unit={unit} slider={false} onValue={y=>onValue({...value,y})}/></fieldset>; }
export function BoundsField({label,value,onValue,unit="px"}:{label:string;value:{x:number;y:number;width:number;height:number};onValue:(value:{x:number;y:number;width:number;height:number})=>void;unit?:string}) { return <fieldset className="bv-compound-field"><legend>{label}</legend>{(["x","y","width","height"] as const).map(key=><NumberField key={key} label={key[0].toUpperCase()+key.slice(1)} value={value[key]} min={key==="width"||key==="height"?0:-999999} max={999999} step={1} unit={unit} slider={false} onValue={next=>onValue({...value,[key]:next})}/>)}</fieldset>; }
