import React,{ReactNode,useId,useState}from"react";
import{Button}from"./actions";
export type TabItem={id:string;label:ReactNode;content:ReactNode;disabled?:boolean};
export function Tabs({items,value,onValue,variant="document",orientation="horizontal",label="Sections"}:{items:TabItem[];value:string;onValue:(id:string)=>void;variant?:"document"|"compact"|"vertical";orientation?:"horizontal"|"vertical";label?:string}){const base=useId();return <div className={`bv-tabs ${variant} ${orientation}`}><div role="tablist" aria-orientation={orientation} aria-label={label}>{items.map(item=><button key={item.id} id={`${base}-${item.id}-tab`} role="tab" aria-selected={value===item.id} aria-controls={`${base}-${item.id}-panel`} tabIndex={value===item.id?0:-1} disabled={item.disabled} onClick={()=>onValue(item.id)}>{item.label}</button>)}</div>{items.map(item=><div key={item.id} id={`${base}-${item.id}-panel`} role="tabpanel" aria-labelledby={`${base}-${item.id}-tab`} hidden={value!==item.id}>{item.content}</div>)}</div>}
export type AccordionItem={id:string;title:ReactNode;content:ReactNode;disabled?:boolean};
export function Accordion({items,value,onValue,exclusive=false}:{items:AccordionItem[];value:string[];onValue:(ids:string[])=>void;exclusive?:boolean}){const toggle=(id:string)=>onValue(value.includes(id)?value.filter(item=>item!==id):exclusive?[id]:[...value,id]);return <div className="bv-accordion">{items.map(item=><section key={item.id} className={item.disabled?"disabled":""}><button type="button" aria-expanded={value.includes(item.id)} disabled={item.disabled} onClick={()=>toggle(item.id)}><span>{item.title}</span><span className="bv-chevron"/></button>{value.includes(item.id)&&<div>{item.content}</div>}</section>)}</div>}
export function Breadcrumbs({items}:{items:Array<{label:ReactNode;onClick?:()=>void}>}){return <nav className="bv-breadcrumbs" aria-label="Breadcrumb">{items.map((item,i)=><React.Fragment key={i}>{i>0&&<span aria-hidden="true">/</span>}{item.onClick?<button type="button" onClick={item.onClick}>{item.label}</button>:<span aria-current="page">{item.label}</span>}</React.Fragment>)}</nav>}
export function Pagination({page,pages,onPage}:{page:number;pages:number;onPage:(page:number)=>void}){return <nav className="bv-pagination" aria-label="Pagination"><Button intent="ghost" disabled={page<=1} onClick={()=>onPage(page-1)}>Previous</Button>{Array.from({length:pages},(_,i)=>i+1).map(item=><Button key={item} intent={item===page?"primary":"ghost"} aria-current={item===page?"page":undefined} onClick={()=>onPage(item)}>{item}</Button>)}<Button intent="ghost" disabled={page>=pages} onClick={()=>onPage(page+1)}>Next</Button></nav>}
export function Steps({items,current}:{items:Array<{label:string;description?:string}>;current:number}){return <ol className="bv-steps">{items.map((item,i)=><li key={item.label} className={i<current?"complete":i===current?"current":""} aria-current={i===current?"step":undefined}><span>{i<current?"✓":i+1}</span><div><strong>{item.label}</strong>{item.description&&<small>{item.description}</small>}</div></li>)}</ol>}
export function Tooltip({content,children}:{content:ReactNode;children:ReactNode}){return <span className="bv-tooltip-host">{children}<span className="bv-tooltip" role="tooltip">{content}</span></span>}

export type DirectoryNode={id:string;label:string;count?:number;children?:DirectoryNode[]};
export function DirectoryTree({nodes,selectedId,expandedIds,onSelect,onExpanded,label="Directories"}:{nodes:DirectoryNode[];selectedId:string;expandedIds:string[];onSelect:(id:string)=>void;onExpanded:(ids:string[])=>void;label?:string}){
    const toggle=(id:string)=>onExpanded(expandedIds.includes(id)?expandedIds.filter(value=>value!==id):[...expandedIds,id]);
    const render=(node:DirectoryNode,level:number):ReactNode=>{
        const expanded=expandedIds.includes(node.id),hasChildren=Boolean(node.children?.length);
        return <li key={node.id} role="treeitem" aria-level={level} aria-selected={selectedId===node.id} aria-expanded={hasChildren?expanded:undefined}><div className="bv-directory-tree-row" style={{"--bv-directory-depth":level-1} as React.CSSProperties}>{hasChildren?<button type="button" className="bv-directory-tree-expander" aria-label={`${expanded?"Collapse":"Expand"} ${node.label}`} onClick={()=>toggle(node.id)}><span className="bv-chevron"/></button>:<span className="bv-directory-tree-spacer"/>}<button type="button" className="bv-directory-tree-select" onClick={()=>onSelect(node.id)}><span>{node.label}</span>{node.count!==undefined&&<small>{node.count}</small>}</button></div>{hasChildren&&expanded&&<ul role="group">{node.children!.map(child=>render(child,level+1))}</ul>}</li>;
    };
    return <nav className="bv-directory-tree" aria-label={label}><ul role="tree">{nodes.map(node=>render(node,1))}</ul></nav>;
}
