import React,{ReactNode,useEffect,useRef,useState}from"react";
import{AnchoredPopover,Portal}from"./floating";
export{AnchoredPopover,Portal}from"./floating";
import{Button,MenuAction}from"./actions";
export function AdaptiveFieldPopover({label,summary,icon,children,popover,className=""}:{label:string;summary:ReactNode;icon?:ReactNode;children:ReactNode;popover:ReactNode;className?:string}){const[open,setOpen]=useState(false),anchor=useRef<HTMLDivElement>(null);return <div ref={anchor} className={`bv-adaptive-field ${className}`.trim()}><div className="bv-adaptive-inline">{children}</div><Button type="button" intent="secondary" className="bv-adaptive-trigger" icon={icon} aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(true)}><span className="bv-adaptive-summary">{summary}</span><span aria-hidden="true">↗</span></Button><AnchoredPopover open={open} anchor={anchor} onClose={()=>setOpen(false)} className="bv-adaptive-popover"><header><strong>{label}</strong><Button type="button" intent="ghost" icon="×" iconOnly aria-label={`Close ${label} editor`} onClick={()=>setOpen(false)}/></header><div>{popover}</div></AnchoredPopover></div>}
export function Dialog({open,title,description,children,footer,onClose,modal=true,size="medium"}:{open:boolean;title:string;description?:ReactNode;children:ReactNode;footer?:ReactNode;onClose:()=>void;modal?:boolean;size?:"small"|"medium"|"large"}){if(!open)return null;return <Portal><div className={`bv-dialog-layer ${modal?"modal":"modeless"}`} role={modal?"presentation":undefined} onPointerDown={e=>{if(modal&&e.target===e.currentTarget)onClose()}}><section className={`bv-dialog ${size}`} role="dialog" aria-modal={modal} aria-label={title}><header><div><h2>{title}</h2>{description&&<p>{description}</p>}</div><Button intent="ghost" icon="×" iconOnly aria-label="Close" onClick={onClose}/></header><div className="bv-dialog-body">{children}</div>{footer&&<footer>{footer}</footer>}</section></div></Portal>}
export function UnsavedChangesDialog({open,editorName,onSave,onDiscard,onKeep}:{open:boolean;editorName:string;onSave:()=>void;onDiscard:()=>void;onKeep:()=>void}){return <Dialog open={open} title="Unsaved changes" description={`${editorName} contains execution changes that have not been saved.`} onClose={onKeep} size="small" footer={<><Button intent="ghost" onClick={onKeep}>Keep editing</Button><Button intent="secondary" onClick={onDiscard}>Discard</Button><Button intent="primary" onClick={onSave}>Save</Button></>}><p>Save the current draft, discard it, or return to the editor.</p></Dialog>}
export function useBvConfirm(){const[request,setRequest]=useState<null|{title:string;message:string;confirmLabel:string;danger:boolean;action:()=>void}>(null);const confirm=(input:{title:string;message:string;confirmLabel?:string;danger?:boolean;action:()=>void})=>setRequest({confirmLabel:"Continue",danger:false,...input});const dialog=<Dialog open={Boolean(request)} title={request?.title??"Confirm action"} onClose={()=>setRequest(null)} size="small" footer={<><Button intent="ghost" onClick={()=>setRequest(null)}>Cancel</Button><Button intent={request?.danger?"danger":"primary"} onClick={()=>{const action=request?.action;setRequest(null);action?.()}}>{request?.confirmLabel}</Button></>}>{request?.message&&<p>{request.message}</p>}</Dialog>;return{confirm,dialog}}
export function Popover({trigger,children,open,onOpen}:{trigger:(props:{open:boolean;toggle:()=>void})=>ReactNode;children:ReactNode;open?:boolean;onOpen?:(open:boolean)=>void}){const[internal,setInternal]=useState(false),anchor=useRef<HTMLSpanElement>(null),visible=open??internal,set=(next:boolean)=>{setInternal(next);onOpen?.(next)};return <span ref={anchor} className="bv-popover-host">{trigger({open:visible,toggle:()=>set(!visible)})}<AnchoredPopover open={visible} anchor={anchor} onClose={()=>set(false)} className="bv-popover">{children}</AnchoredPopover></span>}
export type Command={id:string;label:string;description?:string;group?:string;icon?:ReactNode;shortcut?:string;keywords?:string[];run:()=>void};
export function CommandPalette({open,commands,onClose}:{open:boolean;commands:Command[];onClose:()=>void}){const[query,setQuery]=useState(""),[active,setActive]=useState(0);useEffect(()=>{if(open){setQuery("");setActive(0)}},[open]);const visible=commands.filter(command=>`${command.label} ${command.description??""} ${(command.keywords??[]).join(" ")}`.toLowerCase().includes(query.toLowerCase())),run=(command:Command|undefined)=>{if(!command)return;command.run();onClose()};return <Dialog open={open} title="Command palette" onClose={onClose} size="medium"><div className="bv-command-palette"><span className="bv-input-shell bv-command-input"><span aria-hidden="true">⌕</span><input autoFocus value={query} onChange={e=>{setQuery(e.target.value);setActive(0)}} onKeyDown={event=>{if(event.key==="ArrowDown"){event.preventDefault();setActive(index=>Math.min(visible.length-1,index+1))}else if(event.key==="ArrowUp"){event.preventDefault();setActive(index=>Math.max(0,index-1))}else if(event.key==="Enter"){event.preventDefault();run(visible[active])}}} placeholder="Type a command…"/></span><div className="bv-command-results" role="listbox">{visible.map((command,index)=><button type="button" className="bv-command-option" role="option" aria-selected={index===active} key={command.id} onPointerMove={()=>setActive(index)} onClick={()=>run(command)}>{command.icon&&<span className="bv-command-icon">{command.icon}</span>}<span><strong>{command.label}</strong>{command.description&&<small>{command.description}</small>}</span>{command.shortcut&&<kbd>{command.shortcut}</kbd>}</button>)}{visible.length===0&&<p className="bv-command-empty">No matching commands.</p>}</div></div></Dialog>}
export function ContextMenu({open,x,y,actions,onClose}:{open:boolean;x:number;y:number;actions:MenuAction[];onClose:()=>void}){if(!open)return null;return <Portal><div className="bv-context-menu" role="menu" style={{left:x,top:y}}>{actions.map(action=><button type="button" role="menuitem" key={action.id} disabled={action.disabled} className={action.danger?"danger":""} onClick={()=>{action.onSelect();onClose();}}>{action.icon}<span>{action.label}</span>{action.shortcut&&<kbd>{action.shortcut}</kbd>}</button>)}</div></Portal>}
