import { useEffect, useMemo, useState } from "react";
import { Accordion, Button, BvFooterActions, BvManagedWindow, BvWindowNavigator, Callout, DraftJsonActions, EmptyState, FieldGrid, NumberField, SelectField, SortableItem, SortableList, TagSelect, TextField, UiDensity, UnsavedChangesDialog, useBvHistory, useBvHistoryShortcuts } from "../ui";
import { defaultConditioning, defaultDetection, defaultDetailerPlan, DetailerPlanConfig, DetailerPlanRegion, eligibleDetailerRegions, parseDetailerPlanConfig, serializeDetailerPlanConfig } from "./detailerPlanConfig";
import { setWindowMenuVisible, useWindowMenuVisibility } from "../ui/windowRegistry";
import { DETAILER_V3_INVENTORY_CHANGED_EVENT, detailerV3Catalog } from "./detailerV3Graph";
import { ResourcePicker } from "../ui/components";

const copy = <T,>(value: T): T => structuredClone(value);

export function DetailerPlanDialogView({ regions, collectors=[], stored, save, close, nodeId="", nodes=[], onNavigate=()=>{}, currentNode }: { regions: DetailerPlanRegion[]; collectors?:Array<{id:string;label:string;resources:Array<{id:string;label:string}>}>; detectorIds?:string[]; stored: unknown; save: (value: string) => void; close: () => void; activationToken?: number; nodeId?:string; nodes?:Array<{id:string;label:string}>; onNavigate?:(id:string,replaceCurrent:boolean)=>void; currentNode?:any }) {
    const [liveCollectors,setLiveCollectors]=useState(collectors);useEffect(()=>{const refresh=()=>setLiveCollectors(detailerV3Catalog(currentNode));window.addEventListener(DETAILER_V3_INVENTORY_CHANGED_EVENT,refresh);return()=>window.removeEventListener(DETAILER_V3_INVENTORY_CHANGED_EVENT,refresh)},[currentNode]);collectors=liveCollectors;
    const available = eligibleDetailerRegions(regions);
    const initial=useMemo(()=>parseDetailerPlanConfig(stored,regions,collectors),[regions,stored,collectors]),history=useBvHistory(initial),config=history.value,[baseline,setBaseline]=useState(()=>serializeDetailerPlanConfig(initial));
    useBvHistoryShortcuts(history);
    const dirty=serializeDetailerPlanConfig(config)!==baseline;
    const [pending,setPending]=useState<null|(()=>void)>(null);
    const saveCurrent=()=>{const value=serializeDetailerPlanConfig(config);save(value);setBaseline(value);history.clear()};
    const request=(action:()=>void)=>dirty?setPending(()=>action):action();
    const requestClose=()=>request(close);
    const menuVisible=useWindowMenuVisibility(currentNode);
    const [expanded, setExpanded] = useState<string[]>([]);
    const update = (mutate: (draft: DetailerPlanConfig) => void) => history.commit(current => { const draft = copy(current); mutate(draft); return draft; });
    const add = () => update(draft => { const first = available[0]; if (first) draft.jobs.push({ id:crypto.randomUUID(),region_ids: [first.id], primary_region_id: first.id, mask_composition: "union", prompt_composition: "context", conditioning: defaultConditioning(), detector_assignments:[] }); });
    const items: SortableItem[] = config.jobs.map((job, index) => ({
        id: job.id, title: `Job ${index + 1}`,
        description: job.region_ids.map(id => available.find(region => region.id === id)?.name ?? id).join(" + ") || "No region",
        summary: <div className="bv-editor-item-compact-summary"><span>{job.region_ids.length} region{job.region_ids.length === 1 ? "" : "s"}</span><span>{job.detector_assignments[0]?.source.resource_id || "Composed mask"}</span><span>{job.region_ids.length ? "Ready" : "Needs region"}</span></div>,
        content: <div className="bv-editor-item-details"><div className="bv-editor-item-summary"><TagSelect label="Regions" value={job.region_ids} minSelected={1} options={available.map(region => ({ value: region.id, label: region.name }))} onValue={regionIds => update(draft => { const target = draft.jobs[index]; target.region_ids = regionIds; if (!regionIds.includes(target.primary_region_id)) target.primary_region_id = regionIds[0] ?? ""; })}/><ResourcePicker label="Detector" emptyLabel="No detector · use composed region mask" collectors={collectors} collectorId={job.detector_assignments[0]?.source.collector_id??""} resourceId={job.detector_assignments[0]?.source.resource_id??""} onSelection={(collectorId,resourceId)=>update(draft=>{draft.jobs[index].detector_assignments=collectorId&&resourceId?[{id:draft.jobs[index].detector_assignments[0]?.id??crypto.randomUUID(),source:{collector_id:collectorId,resource_id:resourceId},options:draft.jobs[index].detector_assignments[0]?.options??defaultDetection()}]:[]})}/><FieldGrid>{job.region_ids.length > 1 && <SelectField label="Primary region" value={job.primary_region_id} options={job.region_ids.map(id => ({ value: id, label: available.find(region => region.id === id)?.name ?? id }))} onValue={value => update(draft => { draft.jobs[index].primary_region_id = value; })}/>}</FieldGrid></div><Accordion value={expanded} onValue={setExpanded} items={[
            { id: `composition-${index}`, title: "Mask and prompt composition", content: <FieldGrid><SelectField label="Mask composition" value={job.mask_composition} options={[{value:"union",label:"Union"},{value:"intersection",label:"Intersection"},{value:"subtract",label:"Subtract in listed order"}]} onValue={value => update(draft => { draft.jobs[index].mask_composition = value as typeof job.mask_composition; })}/><SelectField label="Prompt composition" value={job.prompt_composition} options={[{value:"context",label:"Primary and context regions"},{value:"primary",label:"Primary region only"}]} onValue={value => update(draft => { draft.jobs[index].prompt_composition = value as typeof job.prompt_composition; })}/></FieldGrid> },
            { id: `conditioning-${index}`, title: "Conditioning strengths", content: <FieldGrid minimum={150}>{([['Global influence','global_influence'],['Background influence','background_influence'],['Primary region influence','primary_region_influence'],['Context region influence','context_region_influence']] as const).map(([label,key]) => <NumberField key={key} label={label} value={job.conditioning[key]} min={0} max={2} step={.05} onValue={value => update(draft => { draft.jobs[index].conditioning[key] = value; })}/>)}</FieldGrid> },
            { id: `detection-${index}`, title: "Detector and ROI settings", content: job.detector_assignments[0]?<FieldGrid minimum={150}>{Object.entries(job.detector_assignments[0].options).slice(0,5).map(([key,current])=><NumberField key={key} label={key.replaceAll("_"," ")} value={Number(current)} min={key==="dilation"?-512:key==="crop_factor"||key==="drop_size"?1:0} max={key==="threshold"?1:key==="crop_factor"?20:key==="drop_size"?8192:key==="dilation"?512:2} step={["dilation","drop_size"].includes(key)?1:.01} onValue={value=>update(draft=>{(draft.jobs[index].detector_assignments[0].options as any)[key]=value})}/>)}<TextField label="Detector query" value={job.detector_assignments[0].options.query??""} onValue={value=>update(draft=>{draft.jobs[index].detector_assignments[0].options.query=value.trim()||undefined})}/><TextField label="Accepted labels" value={(job.detector_assignments[0].options.labels??[]).join(", ")} onValue={value=>update(draft=>{draft.jobs[index].detector_assignments[0].options.labels=value.split(",").map(v=>v.trim()).filter(Boolean)})}/></FieldGrid>:<Callout tone="info" title="Composed mask">This job has no detector assignment.</Callout> }
        ]}/></div>
    }));
    return <><BvManagedWindow open title="Regional Detailer Plan" shortTitle="Detailer Plan" menuVisible={menuVisible} onMenuVisible={visible=>setWindowMenuVisible(currentNode,visible)} context={<BvWindowNavigator label="Detailer Plan Node" value={nodeId} options={nodes.map(item=>({value:item.id,label:item.label}))} onNavigate={(id,replace)=>replace?request(()=>onNavigate(id,true)):onNavigate(id,false)}/>} initialGeometry={{width:1040,height:720}} minSize={{width:420,height:360}} onClose={requestClose} status={dirty?"Unsaved plan changes":"Plan saved"} actions={<BvFooterActions primary={<Button intent="primary" disabled={config.jobs.some(job => !job.region_ids.length)} onClick={saveCurrent}>Save plan</Button>} secondary={<><Button onClick={add} disabled={!available.length}>Add job</Button><DraftJsonActions label="Detailer Plan" value={{schema:"bv.editor-draft",version:1,type:"detailer-plan",data:config}} onImport={(value:any)=>{if(value?.schema!=="bv.editor-draft"||value?.version!==1||value?.type!=="detailer-plan"||!value?.data)throw new Error("Draft type or version does not match this editor.");history.replace(parseDetailerPlanConfig(value.data,regions,collectors))}}/></>} overflow={[{id:"undo",label:"Undo",disabled:!history.canUndo,onSelect:history.undo},{id:"redo",label:"Redo",disabled:!history.canRedo,onSelect:history.redo},{id:"discard",label:"Discard changes",disabled:!dirty,onSelect:()=>history.replace(parseDetailerPlanConfig(baseline,regions,collectors),true)},{id:"restore",label:"Restore defaults",onSelect:()=>history.commit(defaultDetailerPlan(regions))}]}/>}><UiDensity density="compact" className="bv-editor-dialog">{!collectors.length && config.jobs.length > 0 && <Callout tone="warning" title="No registered detectors">Jobs can still use their composed region masks. Add detectors in Detector Registry when object detection is required.</Callout>}{!available.length ? <EmptyState title="No eligible regions" description="Enable a region with Detailer or Both usage first." /> : <SortableList items={items} onReorder={next => update(draft => { const byId=new Map(draft.jobs.map(job=>[job.id,job]));draft.jobs=next.map(item=>byId.get(item.id)!).filter(Boolean)})} onRemove={id => update(draft => { draft.jobs=draft.jobs.filter(job=>job.id!==id) })}/>}</UiDensity></BvManagedWindow><UnsavedChangesDialog open={Boolean(pending)} editorName="Detailer Plan" onKeep={()=>setPending(null)} onDiscard={()=>{const action=pending;setPending(null);action?.()}} onSave={()=>{saveCurrent();const action=pending;setPending(null);action?.()}}/></>;
}
