import { defaultConditioning, defaultDetection, defaultDetailerPlan, DetailerPlanConfig, DetailerPlanJob, DetailerPlanRegion, eligibleDetailerRegions, parseDetailerPlanConfig, serializeDetailerPlanConfig } from "./detailerPlanConfig";
const el = <K extends keyof HTMLElementTagNameMap>(tag: K, text?: string) => { const value = document.createElement(tag); if (text != null) value.textContent = text; return value; };
const button = (label: string, action: () => void, primary = false) => { const value = el("button", label); value.type = "button"; value.className = primary ? "bv-detailer-button bv-detailer-button-primary" : "bv-detailer-button"; value.onclick = action; return value; };
export const openDetailerPlanDialog = (regions: DetailerPlanRegion[], detectorIds: string[], stored: unknown, save: (value: string) => void) => {
    const available = eligibleDetailerRegions(regions); let config: DetailerPlanConfig = parseDetailerPlanConfig(stored, regions);
    const dialog = el("dialog"); dialog.className = "bv-detailer-dialog";
    const header = el("header"); header.className = "bv-detailer-dialog-header"; header.append(el("h2", "Regional Detailer Plan"), el("p", "Each job is one sequential detail pass. Combine regions when they should share a crop, prompt context, and detector."));
    const list = el("div"); list.className = "bv-detailer-card-list";
    const numberField = (caption: string, value: number, min: number, max: number, step: number, changed: (value: number) => void) => { const input = el("input"); input.type = "number"; input.min = String(min); input.max = String(max); input.step = String(step); input.value = String(value); input.onchange = () => changed(Math.max(min, Math.min(max, Number(input.value)))); const label = el("label", caption); label.className = "bv-detailer-field"; label.append(input); return label; };
    const render = () => {
        list.replaceChildren();
        if (!available.length) list.append(el("div", "No enabled Detailer or Both regions are available."));
        config.jobs.forEach((job, index) => {
            const card = el("section"); card.className = "bv-detailer-card";
            const head = el("div"); head.className = "bv-detailer-card-header"; const title = el("strong", `Job ${index + 1}`); title.className = "bv-detailer-card-title";
            head.append(title, button("Move up", () => { if (index) [config.jobs[index - 1], config.jobs[index]] = [job, config.jobs[index - 1]]; render(); }), button("Move down", () => { if (index + 1 < config.jobs.length) [config.jobs[index + 1], config.jobs[index]] = [job, config.jobs[index + 1]]; render(); }), button("Remove", () => { config.jobs.splice(index, 1); render(); }));
            const regionGrid = el("div"); regionGrid.className = "bv-detailer-region-grid";
            for (const region of available) { const label = el("label"); label.className = "bv-detailer-region-choice"; const checkbox = el("input"); checkbox.type = "checkbox"; checkbox.checked = job.region_ids.includes(region.id); checkbox.onchange = () => { job.region_ids = checkbox.checked ? [...job.region_ids, region.id] : job.region_ids.filter(id => id !== region.id); if (!job.region_ids.includes(job.primary_region_id)) job.primary_region_id = job.region_ids[0] ?? ""; render(); }; label.append(checkbox, ` ${region.name}`); regionGrid.append(label); }
            const controls = el("div"); controls.className = "bv-detailer-control-grid";
            const selectField = (caption: string, values: Array<[string, string]>, current: string, changed: (value: string) => void) => { const label = el("label", caption); label.className = "bv-detailer-field"; const select = el("select"); for (const [value, text] of values) { const option = el("option", text); option.value = value; option.selected = value === current; select.append(option); } select.onchange = () => changed(select.value); label.append(select); controls.append(label); };
            selectField("Primary region", job.region_ids.map(id => [id, available.find(region => region.id === id)?.name ?? id]), job.primary_region_id, value => job.primary_region_id = value);
            selectField("Mask composition", [["union", "Union"], ["intersection", "Intersection"], ["subtract", "Subtract in listed order"]], job.mask_composition, value => job.mask_composition = value as any);
            selectField("Prompt composition", [["context", "Primary and context regions"], ["primary", "Primary region only"]], job.prompt_composition, value => job.prompt_composition = value as any);
            const detectorChoices = [...new Set([...(job.detector_id && !detectorIds.includes(job.detector_id) ? [job.detector_id] : []), ...detectorIds])]; selectField("Detector", [["", "No detector"], ...detectorChoices.map(id => [id, detectorIds.includes(id) ? id : `Missing · ${id}`] as [string, string])], job.detector_id ?? "", value => job.detector_id = value || undefined);
            const conditioning = el("details"); conditioning.className = "bv-detailer-settings"; conditioning.append(el("summary", "Conditioning strengths")); const conditioningGrid = el("div"); conditioningGrid.className = "bv-detailer-control-grid"; conditioningGrid.append(numberField("Global influence", job.conditioning.global_influence, 0, 2, .05, value => job.conditioning.global_influence = value), numberField("Background influence", job.conditioning.background_influence, 0, 2, .05, value => job.conditioning.background_influence = value), numberField("Primary region influence", job.conditioning.primary_region_influence, 0, 2, .05, value => job.conditioning.primary_region_influence = value), numberField("Context region influence", job.conditioning.context_region_influence, 0, 2, .05, value => job.conditioning.context_region_influence = value)); conditioning.append(conditioningGrid);
            const detection = el("details"); detection.className = "bv-detailer-settings"; detection.append(el("summary", "Detector and ROI settings")); const detectionGrid = el("div"); detectionGrid.className = "bv-detailer-control-grid"; detectionGrid.append(numberField("ROI padding", job.detector.roi_padding, 0, 2, .01, value => job.detector.roi_padding = value), numberField("Threshold", job.detector.threshold, 0, 1, .01, value => job.detector.threshold = value), numberField("Dilation", job.detector.dilation, -512, 512, 1, value => job.detector.dilation = value), numberField("Crop factor", job.detector.crop_factor, 1, 20, .1, value => job.detector.crop_factor = value), numberField("Drop size", job.detector.drop_size, 1, 8192, 1, value => job.detector.drop_size = value));
            for (const [caption, key, placeholder] of [["Detector query", "query", "Optional text query"], ["Accepted labels", "labels", "Comma-separated labels"]] as const) { const input = el("input"); input.placeholder = placeholder; input.value = key === "labels" ? (job.detector.labels ?? []).join(", ") : job.detector.query ?? ""; input.onchange = () => { if (key === "labels") job.detector.labels = input.value.split(",").map(value => value.trim()).filter(Boolean); else job.detector.query = input.value.trim() || undefined; }; const label = el("label", caption); label.className = "bv-detailer-field"; label.append(input); detectionGrid.append(label); } detection.append(detectionGrid);
            card.append(head, el("div", "Regions"), regionGrid, controls, conditioning, detection); list.append(card);
        });
    };
    const footer = el("footer"); footer.className = "bv-detailer-dialog-footer"; footer.append(button("Restore defaults", () => { config = defaultDetailerPlan(regions); render(); }), button("Add job", () => { const first = available[0]; if (first) { config.jobs.push({ region_ids: [first.id], primary_region_id: first.id, mask_composition: "union", prompt_composition: "context", conditioning: defaultConditioning(), detector: defaultDetection() }); render(); } }), button("Cancel", () => dialog.close()), button("Save plan", () => { if (!config.jobs.some(job => !job.region_ids.length)) { save(serializeDetailerPlanConfig(config)); dialog.close(); } }, true));
    dialog.addEventListener("close", () => dialog.remove()); dialog.append(header, list, footer); document.body.append(dialog); render(); dialog.showModal();
};
