import { useMemo, useState, type ComponentProps } from "react";
import { Accordion, Button, BvManagedWindow as BaseBvManagedWindow, BvWindowNavigator, Callout, EmptyState, FieldGrid, NumberField, SelectField, SortableItem, SortableList, TagSelect, TextField, UiDensity } from "../ui";
import { defaultConditioning, defaultDetection, defaultDetailerPlan, DetailerPlanConfig, DetailerPlanRegion, eligibleDetailerRegions, parseDetailerPlanConfig, serializeDetailerPlanConfig } from "./detailerPlanConfig";

const copy = <T,>(value: T): T => structuredClone(value);

export function DetailerPlanDialogView({ regions, detectorIds, stored, save, close, nodeId="", nodes=[], onNavigate=()=>{} }: { regions: DetailerPlanRegion[]; detectorIds: string[]; stored: unknown; save: (value: string) => void; close: () => void; activationToken?: number; nodeId?:string; nodes?:Array<{id:string;label:string}>; onNavigate?:(id:string,replaceCurrent:boolean)=>void }) {
    const available = eligibleDetailerRegions(regions);
    const [config, setConfig] = useState<DetailerPlanConfig>(() => parseDetailerPlanConfig(stored, regions));
    const dirty=serializeDetailerPlanConfig(config)!==serializeDetailerPlanConfig(parseDetailerPlanConfig(stored,regions));
    const requestClose=()=>{if(!dirty||window.confirm("Discard unsaved Detailer Plan changes?"))close()};
    const BvManagedWindow=useMemo(()=>(props:ComponentProps<typeof BaseBvManagedWindow>)=><BaseBvManagedWindow {...props} title={`${props.title} · #${nodeId}`} onClose={requestClose} context={<BvWindowNavigator label="Detailer Plan Node" value={nodeId} options={nodes.map(item=>({value:item.id,label:item.label}))} onNavigate={(id,replace)=>{if(!replace||!dirty||window.confirm("Discard unsaved Detailer Plan changes?"))onNavigate(id,replace)}}/>}/>,[dirty,nodeId,nodes,onNavigate]);
    const [expanded, setExpanded] = useState<string[]>([]);
    const update = (mutate: (draft: DetailerPlanConfig) => void) => setConfig(current => { const draft = copy(current); mutate(draft); return draft; });
    const add = () => update(draft => { const first = available[0]; if (first) draft.jobs.push({ region_ids: [first.id], primary_region_id: first.id, mask_composition: "union", prompt_composition: "context", conditioning: defaultConditioning(), detector: defaultDetection() }); });
    const detectorOptions = (current?: string) => [{ value: "", label: "No detector · use composed region mask" }, ...[...new Set([...(current && !detectorIds.includes(current) ? [current] : []), ...detectorIds])].map(id => ({ value: id, label: detectorIds.includes(id) ? id : `Missing · ${id}` }))];
    const items: SortableItem[] = config.jobs.map((job, index) => ({
        id: `job-${index}`, title: `Job ${index + 1}`,
        description: job.region_ids.map(id => available.find(region => region.id === id)?.name ?? id).join(" + ") || "No region",
        summary: <div className="bv-editor-item-summary"><TagSelect label="Regions" value={job.region_ids} minSelected={1} options={available.map(region => ({ value: region.id, label: region.name }))} onValue={regionIds => update(draft => { const target = draft.jobs[index]; target.region_ids = regionIds; if (!regionIds.includes(target.primary_region_id)) target.primary_region_id = regionIds[0] ?? ""; })}/><FieldGrid><SelectField label="Detector assignment" value={job.detector_id ?? ""} options={detectorOptions(job.detector_id)} onValue={value => update(draft => { draft.jobs[index].detector_id = value || undefined; })}/>{job.region_ids.length > 1 && <SelectField label="Primary region" value={job.primary_region_id} options={job.region_ids.map(id => ({ value: id, label: available.find(region => region.id === id)?.name ?? id }))} onValue={value => update(draft => { draft.jobs[index].primary_region_id = value; })}/>}</FieldGrid></div>,
        content: <Accordion value={expanded} onValue={setExpanded} items={[
            { id: `composition-${index}`, title: "Mask and prompt composition", content: <FieldGrid><SelectField label="Mask composition" value={job.mask_composition} options={[{value:"union",label:"Union"},{value:"intersection",label:"Intersection"},{value:"subtract",label:"Subtract in listed order"}]} onValue={value => update(draft => { draft.jobs[index].mask_composition = value as typeof job.mask_composition; })}/><SelectField label="Prompt composition" value={job.prompt_composition} options={[{value:"context",label:"Primary and context regions"},{value:"primary",label:"Primary region only"}]} onValue={value => update(draft => { draft.jobs[index].prompt_composition = value as typeof job.prompt_composition; })}/></FieldGrid> },
            { id: `conditioning-${index}`, title: "Conditioning strengths", content: <FieldGrid minimum={150}>{([['Global influence','global_influence'],['Background influence','background_influence'],['Primary region influence','primary_region_influence'],['Context region influence','context_region_influence']] as const).map(([label,key]) => <NumberField key={key} label={label} value={job.conditioning[key]} min={0} max={2} step={.05} onValue={value => update(draft => { draft.jobs[index].conditioning[key] = value; })}/>)}</FieldGrid> },
            { id: `detection-${index}`, title: "Detector and ROI settings", content: <FieldGrid minimum={150}><NumberField label="ROI padding" value={job.detector.roi_padding} min={0} max={2} step={.01} onValue={value => update(draft => { draft.jobs[index].detector.roi_padding = value; })}/><NumberField label="Threshold" value={job.detector.threshold} min={0} max={1} step={.01} onValue={value => update(draft => { draft.jobs[index].detector.threshold = value; })}/><NumberField label="Dilation" value={job.detector.dilation} min={-512} max={512} step={1} slider={false} onValue={value => update(draft => { draft.jobs[index].detector.dilation = value; })}/><NumberField label="Crop factor" value={job.detector.crop_factor} min={1} max={20} step={.1} onValue={value => update(draft => { draft.jobs[index].detector.crop_factor = value; })}/><NumberField label="Drop size" value={job.detector.drop_size} min={1} max={8192} step={1} slider={false} onValue={value => update(draft => { draft.jobs[index].detector.drop_size = value; })}/><TextField label="Detector query" value={job.detector.query ?? ""} onValue={value => update(draft => { draft.jobs[index].detector.query = value.trim() || undefined; })}/><TextField label="Accepted labels" value={(job.detector.labels ?? []).join(", ")} onValue={value => update(draft => { draft.jobs[index].detector.labels = value.split(",").map(item => item.trim()).filter(Boolean); })}/></FieldGrid> }
        ]}/>
    }));
    return <BvManagedWindow open title="Regional Detailer Plan" initialGeometry={{width:1040,height:720}} minSize={{width:420,height:360}} onClose={close} status="Jobs run from top to bottom; expand a job for composition and tuning." actions={<><Button intent="ghost" onClick={() => setConfig(defaultDetailerPlan(regions))}>Restore defaults</Button><Button onClick={add} disabled={!available.length}>Add job</Button><Button intent="ghost" onClick={close}>Cancel</Button><Button intent="primary" disabled={config.jobs.some(job => !job.region_ids.length)} onClick={() => { save(serializeDetailerPlanConfig(config)); close(); }}>Save plan</Button></>}><UiDensity density="compact" className="bv-editor-dialog">{!detectorIds.length && config.jobs.length > 0 && <Callout tone="warning" title="No registered detectors">Jobs can still use their composed region masks. Add detectors in Detector Registry when object detection is required.</Callout>}{!available.length ? <EmptyState title="No eligible regions" description="Enable a region with Detailer or Both usage first." /> : <SortableList items={items} onReorder={next => update(draft => { draft.jobs = next.map(item => draft.jobs[Number(item.id.slice(4))]); })} onRemove={id => update(draft => { draft.jobs.splice(Number(id.slice(4)), 1); })}/>}</UiDensity></BvManagedWindow>;
}
