import { useMemo, useState, type ComponentProps } from "react";
import { Accordion, Button, BvFooterActions, BvManagedWindow as BaseBvManagedWindow, BvWindowNavigator, Callout, EmptyState, FieldGrid, SelectField, TextField, UiDensity } from "../ui";
import { DetectorModelCatalog, DetectorRegistryConfig, emptyDetectorRegistryConfig, parseDetectorRegistryConfig, serializeDetectorRegistryConfig } from "./detectorRegistryConfig";

export function DetectorRegistryDialogView({ catalog, stored, save, close, nodeId="", nodes=[], onNavigate=()=>{} }: { catalog: DetectorModelCatalog; stored: unknown; save: (value: string) => void; close: () => void; activationToken?: number; nodeId?:string; nodes?:Array<{id:string;label:string}>; onNavigate?:(id:string,replaceCurrent:boolean)=>void }) {
    const initial = useMemo(() => parseDetectorRegistryConfig(stored), [stored]);
    const persistedIds = useMemo(() => new Set(initial.detectors.map(entry => entry.id)), [initial]);
    const [config, setConfig] = useState<DetectorRegistryConfig>(initial);
    const dirty=serializeDetectorRegistryConfig(config)!==serializeDetectorRegistryConfig(initial);
    const requestClose=()=>{if(!dirty||window.confirm("Discard unsaved Detector Registry changes?"))close()};
    const BvManagedWindow=useMemo(()=>(props:ComponentProps<typeof BaseBvManagedWindow>)=><BaseBvManagedWindow {...props} title={`${props.title} · #${nodeId}`} shortTitle="Registry" onClose={requestClose} context={<BvWindowNavigator label="Detector Registry Node" value={nodeId} options={nodes.map(item=>({value:item.id,label:item.label}))} onNavigate={(id,replace)=>{if(!replace||!dirty||window.confirm("Discard unsaved Detector Registry changes?"))onNavigate(id,replace)}}/>}/>,[dirty,nodeId,nodes,onNavigate]);
    const [expanded, setExpanded] = useState<string[]>([]);
    const update = (mutate: (draft: DetectorRegistryConfig) => void) => setConfig(current => { const draft = structuredClone(current); mutate(draft); return draft; });
    const nextId = () => { let index = config.detectors.length + 1, id = `detector-${index}`; while (config.detectors.some(entry => entry.id === id)) id = `detector-${++index}`; return id; };
    const ids = config.detectors.map(entry => entry.id.trim());
    const duplicate = ids.find((id, index) => id && ids.indexOf(id) !== index);
    const invalid = config.detectors.some(entry => !entry.id.trim() || !entry.model_name);
    const add = () => update(draft => { const provider = catalog.ultralytics.length ? "ultralytics" : "onnx"; draft.detectors.push({ id: nextId(), provider, model_name: catalog[provider][0] ?? "" }); });
    const clear=()=>{if(!config.detectors.length||window.confirm("Remove every detector from this registry? Existing Detailer jobs will keep missing references until reassigned."))setConfig(emptyDetectorRegistryConfig())};
    return <BvManagedWindow open title="Detector Registry" initialGeometry={{width:1040,height:720}} minSize={{width:420,height:360}} onClose={close} status="Stable detector IDs connect installed Impact models to Regional Detailer jobs." actions={<BvFooterActions primary={<Button intent="primary" disabled={Boolean(duplicate || invalid)} onClick={() => { save(serializeDetectorRegistryConfig(config)); close(); }}>Save registry</Button>} secondary={<Button onClick={add}>Add detector</Button>} overflow={[{id:"add",label:"Add detector",onSelect:add},{id:"clear",label:"Clear registry…",onSelect:clear}]}/> }>
        <UiDensity density="compact" className="bv-editor-dialog">
            {(duplicate || invalid) ? <Callout tone="danger" title="Registry needs attention">{duplicate ? `Detector ID “${duplicate}” is used more than once.` : "Every detector needs a unique ID and a detection model."}</Callout> : <Callout tone="success" title="Registry valid">{config.detectors.length} detector{config.detectors.length === 1 ? "" : "s"} ready to save.</Callout>}
            <div className="bv-card-list">{!config.detectors.length && <EmptyState title="No detectors configured" description="Add a detector to make it selectable in Regional Detailer jobs." />}<Accordion value={expanded} onValue={setExpanded} items={config.detectors.map((entry, index) => ({id:`detector-${index}`,title:<span className="bv-detector-summary"><strong>{entry.id || "New detector"}</strong><span>{entry.provider === "onnx" ? "ONNX" : "Ultralytics"}</span><span>{entry.model_name || "No model selected"}</span><span>{entry.id.trim() && entry.model_name ? "Ready" : "Needs attention"}</span></span>,content:<div className="bv-detector-details"><div className="bv-editor-item-actions"><Button intent="ghost" onClick={() => update(draft => { draft.detectors.splice(index + 1, 0, { ...draft.detectors[index], id: nextId() }); })}>Duplicate</Button><Button intent="ghost" className="bv-subtle-danger" onClick={() => { if (persistedIds.has(entry.id) && !window.confirm(`Remove detector “${entry.id}”? Existing Detailer jobs will show it as missing until reassigned.`)) return; update(draft => { draft.detectors.splice(index, 1); }); }}>Remove</Button></div><FieldGrid><TextField label="Detector ID" value={entry.id} readOnly={persistedIds.has(entry.id)} help={persistedIds.has(entry.id) ? "Stable job reference. Create a new detector instead of renaming it." : "Choose once; the ID becomes immutable after saving."} onValue={value => update(draft => { draft.detectors[index].id = value.trim(); })}/><SelectField label="Provider" value={entry.provider} options={[{value:"ultralytics",label:"Ultralytics"},{value:"onnx",label:"ONNX"}]} onValue={value => update(draft => { const target = draft.detectors[index]; target.provider = value as typeof target.provider; target.model_name = catalog[target.provider][0] ?? ""; })}/><SelectField label="Detection model" value={entry.model_name} options={catalog[entry.provider].map(value => ({value,label:value}))} onValue={value => update(draft => { draft.detectors[index].model_name = value; })}/></FieldGrid><Accordion value={expanded} onValue={setExpanded} items={[{ id:`sam-${index}`, title: entry.sam_model_name ? "SAM refinement enabled" : "Optional SAM refinement", content:<FieldGrid><SelectField label="SAM model" value={entry.sam_model_name ?? ""} options={[{value:"",label:"No SAM refinement"},...catalog.sam.map(value => ({value,label:value}))]} onValue={value => update(draft => { const target=draft.detectors[index];target.sam_model_name=value||undefined;if(!value)delete target.sam_device_mode;})}/>{entry.sam_model_name && <SelectField label="Execution device" value={entry.sam_device_mode ?? "AUTO"} options={["AUTO","Prefer GPU","CPU"].map(value => ({value,label:value}))} onValue={value => update(draft => { draft.detectors[index].sam_device_mode=value as "AUTO"|"Prefer GPU"|"CPU"; })}/>}</FieldGrid>}]} /></div>}))}/></div>
        </UiDensity>
    </BvManagedWindow>;
}
