import{useMemo,useRef,useSyncExternalStore}from"react";
import{Button,CompactResourceGroup,CompactResourceList,CompactResourceRow,CompactSortableRows,CompactSquareSwitch,CompactStrengthField,createScrubSnapshotSession,HoverPreview,NumberScrubber,UiDensity}from"../ui";
import{loraCatalogClient}from"./loraCatalogClient";
import{activeLoraCount,applyEntryStrengthDelta,applyStackStrengthDelta,moveLoraEntry,parseLoraRegistryConfig,readSharedStrength,serializeLoraRegistryConfig,writeSharedStrength,writeStackStrength,type LoraCatalog,type LoraRegistryConfig,type LoraRegistryStack}from"./loraRegistryConfig";

const catalogItem=(catalog:LoraCatalog,name:string)=>catalog.items.find(item=>item.name===name);
const label=(name:string)=>name.replace(/\\/g,"/").split("/").slice(-1)[0]?.replace(/\.safetensors$/i,"")||name;
const stackStrength=(stack:LoraRegistryStack)=>{if(!stack.entries.length)return null;const first=stack.entries[0].model_strength;return stack.entries.every(entry=>entry.model_strength===first&&entry.clip_strength===first)?first:null};

export function LoraRegistryNodeView({stored,onStored,onOpenLibrary}:{stored:unknown;onStored:(value:string)=>void;onOpenLibrary:(stackId:string)=>void}){
    const config=useMemo(()=>parseLoraRegistryConfig(stored),[stored]),current=useRef(config),scrub=useRef(createScrubSnapshotSession<LoraRegistryConfig>()).current,catalog=useSyncExternalStore(loraCatalogClient.subscribe,loraCatalogClient.getSnapshot,loraCatalogClient.getSnapshot);current.current=config;
    const store=(next:LoraRegistryConfig)=>{current.current=next;onStored(serializeLoraRegistryConfig(next))},commit=(mutate:(draft:LoraRegistryConfig)=>void)=>{const draft=structuredClone(current.current);mutate(draft);store(draft)},stackById=(draft:LoraRegistryConfig,id:string)=>draft.stacks.find(stack=>stack.id===id),scrubStart=()=>scrub.start(current.current),scrubEnd=()=>scrub.end(),scrubCancel=()=>scrub.cancel(store);
    return <UiDensity density="compact"><CompactResourceList empty="No stacks yet. Open the registry to add one.">{config.stacks.length?config.stacks.map(stack=><CompactResourceGroup key={stack.id} control={<CompactSquareSwitch label={`${stack.name} stack`} value={stack.enabled} onValue={enabled=>commit(draft=>{const target=stackById(draft,stack.id);if(target)target.enabled=enabled})}/>} title={stack.name} meta={stack.enabled?`${activeLoraCount(stack)} active`:`${stack.entries.length} off`} actions={stack.entries.length?<NumberScrubber label={`${stack.name} group strength`} value={stackStrength(stack)} onValue={value=>store(writeStackStrength(current.current,stack.id,value))} onDelta={delta=>store(applyStackStrengthDelta(current.current,stack.id,delta))} onScrubStart={scrubStart} onScrubEnd={scrubEnd} onScrubCancel={scrubCancel}/>:null}><CompactSortableRows items={stack.entries} label={`Reorder ${stack.name} LoRA`} onReorder={entries=>commit(draft=>{const target=stackById(draft,stack.id);if(target)target.entries=entries})} renderRow={(entry,index,dragHandle)=>{const item=catalogItem(catalog,entry.lora_name),name=item?.display_name||label(entry.lora_name),shared=readSharedStrength(entry);return <CompactResourceRow control={<CompactSquareSwitch label={name} value={entry.enabled} onValue={enabled=>commit(draft=>{const target=stackById(draft,stack.id)?.entries.find(value=>value.id===entry.id);if(target)target.enabled=enabled})}/>} dragHandle={dragHandle} title={<HoverPreview src={item?.preview_url} safe={item?.preview_safe} label={name}><span title={name}>{name}</span></HoverPreview>} values={<CompactStrengthField shared={shared.kind==="value"?shared.value:null} model={entry.model_strength} clip={entry.clip_strength} onShared={value=>commit(draft=>{const target=stackById(draft,stack.id)?.entries.find(value=>value.id===entry.id);if(target)Object.assign(target,writeSharedStrength(target,value))})} onDelta={delta=>store(applyEntryStrengthDelta(current.current,stack.id,entry.id,delta))} onScrubStart={scrubStart} onScrubEnd={scrubEnd} onScrubCancel={scrubCancel} onModel={value=>commit(draft=>{const target=stackById(draft,stack.id)?.entries.find(value=>value.id===entry.id);if(target)target.model_strength=value})} onClip={value=>commit(draft=>{const target=stackById(draft,stack.id)?.entries.find(value=>value.id===entry.id);if(target)target.clip_strength=value})}/>} actions={[
        {id:"up",label:"Move up",disabled:index===0,onSelect:()=>store(moveLoraEntry(current.current,stack.id,entry.id,stack.entries[index-1]?.id??entry.id,"before"))},
        {id:"down",label:"Move down",disabled:index===stack.entries.length-1,onSelect:()=>store(moveLoraEntry(current.current,stack.id,entry.id,stack.entries[index+1]?.id??entry.id,"after"))},
        {id:"remove",label:"Remove from stack",danger:true,onSelect:()=>commit(draft=>{const target=stackById(draft,stack.id);if(target)target.entries=target.entries.filter(value=>value.id!==entry.id)})},
    ]}/>}}/><Button density="compact" intent="ghost" className="bv-compact-resource-add" onClick={()=>onOpenLibrary(stack.id)}>＋ Add LoRA</Button></CompactResourceGroup>):null}</CompactResourceList></UiDensity>;
}
