import React,{createElement,useEffect,useMemo,useRef,useState}from"react";
import{getApi}from"../appHelper.js";
import{Button,BvManagedWindow,Callout,CompactSelect,EmptyState,OptionSet,TextField,UiDensity,mountBvView}from"../ui";
import{canonicalLutPath,lutLibrary}from"./lutLibrary";

type CatalogChannel="stable"|"experimental";
type RefreshPhase="idle"|"queued"|"checking"|"up_to_date"|"updated"|"failed";
type RefreshStatus={phase:RefreshPhase;generation:number;effective_source?:string|null;effective_version?:number|null;last_error?:string|null};
type DownloadItem={id:string;name:string;category:string;description:string;recommended_strength:number;input_profile:string;source_name:string;source_url:string;license_label:string;license_url:string;installed?:boolean};
type CatalogPayload={entries:DownloadItem[];channel:CatalogChannel;catalog_version:number;selected_channel:CatalogChannel;refresh_status:RefreshStatus};
type DownloadCategory={id:string;label:string;notice:string;load:(channel?:CatalogChannel)=>Promise<CatalogPayload>;install:(item:DownloadItem,channel:CatalogChannel,catalogVersion:number)=>Promise<string>};
type StatusFilter="all"|"available"|"installed";

const json=async(response:Response)=>{const value=await response.json().catch(()=>null);if(!response.ok)throw new Error(value?.error??String(value??response.statusText));return value};
const LUT_CATEGORY:DownloadCategory={
    id:"luts",
    label:"LUTs",
    notice:"Curated direct downloads. License information is advisory; verify the linked source terms for your use case.",
    load:async channel=>{
        const suffix=channel?`?channel=${encodeURIComponent(channel)}`:"";
        const value=await json(await getApi().fetchApi(`/bv_nodepack/luts/catalog${suffix}`));
        return{...value,entries:Array.isArray(value?.entries)?value.entries:[]};
    },
    install:async(item,channel,catalogVersion)=>{
        const value=await json(await getApi().fetchApi("/bv_nodepack/luts/install",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,channel,catalog_version:catalogVersion})}));
        return String(value.installed.relative_path);
    },
};
export const DOWNLOAD_CATEGORIES:DownloadCategory[]=[LUT_CATEGORY];

const CHANNEL_OPTIONS=[{value:"stable",label:"Stable"},{value:"experimental",label:"Experimental"}];
const running=(status?:RefreshStatus)=>status?.phase==="queued"||status?.phase==="checking";
const statusLabel=(status?:RefreshStatus)=>status?.phase==="checking"?"Checking for catalog updates…":status?.phase==="queued"?"Catalog update queued…":status?.phase==="updated"?`Catalog updated to v${status.effective_version??"?"}`:status?.phase==="up_to_date"?`Catalog v${status.effective_version??"?"} is current`:status?.phase==="failed"?"Using the last valid local catalog":"Catalog ready";
export const isCurrentCatalogRequest=(currentGeneration:number,requestGeneration:number)=>currentGeneration===requestGeneration;
export const catalogPollDecision=(attempt:number,currentGeneration:number,requestGeneration:number)=>!isCurrentCatalogRequest(currentGeneration,requestGeneration)?"stale":attempt>=60?"timeout":"schedule";
export const catalogItemKey=(channel:CatalogChannel,catalogVersion:number,itemId:string)=>`${channel}:${catalogVersion}:${itemId}`;

function DownloadManager({close,onInstalled,initialCategory="luts"}:{close:()=>void;onInstalled?:(category:string,path:string)=>void;initialCategory?:string}){
    const[categoryId,setCategoryId]=useState(initialCategory),[entries,setEntries]=useState<DownloadItem[]>([]),[query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState<StatusFilter>("all"),[busy,setBusy]=useState<Set<string>>(new Set()),[messages,setMessages]=useState<Record<string,string>>({}),[error,setError]=useState("");
    const[channel,setChannel]=useState<CatalogChannel>("stable"),[catalogVersion,setCatalogVersion]=useState(1),[refreshStatus,setRefreshStatus]=useState<RefreshStatus>({phase:"idle",generation:0}),[switching,setSwitching]=useState(false);
    const generation=useRef(0),pollTimer=useRef<number|undefined>();
    const category=DOWNLOAD_CATEGORIES.find(item=>item.id===categoryId)??DOWNLOAD_CATEGORIES[0];

    const applyCatalog=(value:CatalogPayload,requestGeneration:number)=>{if(!isCurrentCatalogRequest(generation.current,requestGeneration))return false;setEntries(value.entries);setChannel(value.channel);setCatalogVersion(value.catalog_version);setRefreshStatus(value.refresh_status);return true};
    const loadCatalog=async(requestGeneration:number,nextChannel?:CatalogChannel)=>applyCatalog(await category.load(nextChannel),requestGeneration);
    const stopPolling=()=>{if(pollTimer.current!==undefined){window.clearTimeout(pollTimer.current);pollTimer.current=undefined}};
    const poll=(activeChannel:CatalogChannel,requestGeneration:number,attempt=0)=>{stopPolling();const decision=catalogPollDecision(attempt,generation.current,requestGeneration);if(decision==="stale")return;if(decision==="timeout"){setRefreshStatus(current=>({...current,phase:"failed",last_error:"Catalog refresh is still running. Try again shortly."}));return}pollTimer.current=window.setTimeout(async()=>{try{const value=await json(await getApi().fetchApi("/bv_nodepack/luts/catalog/status"));if(!isCurrentCatalogRequest(generation.current,requestGeneration))return;const next=value.channels?.[activeChannel] as RefreshStatus|undefined;if(next)setRefreshStatus(next);if(running(next))poll(activeChannel,requestGeneration,attempt+1);else await loadCatalog(requestGeneration,activeChannel)}catch(reason){if(isCurrentCatalogRequest(generation.current,requestGeneration)){const message=String(reason instanceof Error?reason.message:reason);setError(message);setRefreshStatus(current=>({...current,phase:"failed",last_error:message}))}}},500)};

    useEffect(()=>{const requestGeneration=++generation.current;setEntries([]);setError("");category.load().then(value=>{if(!applyCatalog(value,requestGeneration))return;if(running(value.refresh_status))poll(value.channel,requestGeneration)}).catch(reason=>{if(generation.current===requestGeneration)setError(String(reason instanceof Error?reason.message:reason))});return()=>{generation.current++;stopPolling()}},[categoryId]);

    const changeChannel=async(value:string)=>{const next=value as CatalogChannel,requestGeneration=++generation.current;stopPolling();setSwitching(true);setError("");try{const response=await getApi().fetchApi("/bv_nodepack/luts/catalog/channel",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({channel:next})});const changed=await json(response);if(generation.current!==requestGeneration)return;await loadCatalog(requestGeneration,next);setRefreshStatus(current=>({...current,...changed.refresh,phase:"queued"}));poll(next,requestGeneration)}catch(reason){if(generation.current===requestGeneration)setError(String(reason instanceof Error?reason.message:reason))}finally{if(generation.current===requestGeneration)setSwitching(false)}};
    const refreshCatalog=async()=>{const requestGeneration=++generation.current;stopPolling();setError("");try{const value=await json(await getApi().fetchApi("/bv_nodepack/luts/catalog/refresh",{method:"POST"}));if(generation.current!==requestGeneration)return;const activeChannel=value.channel as CatalogChannel;await loadCatalog(requestGeneration,activeChannel);setRefreshStatus(current=>({...current,...value,phase:"queued"}));poll(activeChannel,requestGeneration)}catch(reason){if(generation.current===requestGeneration)setError(String(reason instanceof Error?reason.message:reason))}};
    const reload=()=>{const requestGeneration=++generation.current;stopPolling();loadCatalog(requestGeneration,channel).catch(reason=>{if(isCurrentCatalogRequest(generation.current,requestGeneration))setError(String(reason instanceof Error?reason.message:reason))})};

    const visible=useMemo(()=>{const needle=query.trim().toLowerCase();return entries.filter(item=>{const statusMatches=statusFilter==="all"||(statusFilter==="installed"?item.installed:!item.installed),queryMatches=!needle||`${item.name} ${item.category} ${item.description} ${item.source_name}`.toLowerCase().includes(needle);return statusMatches&&queryMatches})},[entries,query,statusFilter]);
    const install=async(item:DownloadItem)=>{const listedChannel=channel,listedVersion=catalogVersion,itemKey=catalogItemKey(listedChannel,listedVersion,item.id),installGeneration=generation.current;setBusy(current=>new Set(current).add(itemKey));setMessages(current=>({...current,[itemKey]:"Downloading…"}));try{const path=canonicalLutPath(await category.install(item,listedChannel,listedVersion));setMessages(current=>({...current,[itemKey]:"Installed"}));if(category.id==="luts")lutLibrary.publish(path);onInstalled?.(category.id,path);if(isCurrentCatalogRequest(generation.current,installGeneration))reload()}catch(reason){setMessages(current=>({...current,[itemKey]:String(reason instanceof Error?reason.message:reason)}))}finally{setBusy(current=>{const next=new Set(current);next.delete(itemKey);return next})}};
    const context=<><CompactSelect className="bv-download-category-select" label="Download category" value={category.id} options={DOWNLOAD_CATEGORIES.map(item=>({value:item.id,label:item.label}))} onValue={setCategoryId}/><CompactSelect label="Catalog channel" value={channel} options={CHANNEL_OPTIONS} onValue={changeChannel}/></>;
    const availableCount=entries.filter(item=>!item.installed).length,installedCount=entries.length-availableCount;
    return <BvManagedWindow open title="BV Download Manager" shortTitle="Downloads" context={context} initialGeometry={{width:1040,height:720}} minSize={{width:420,height:360}} onClose={close} status={statusLabel(refreshStatus)} actions={<Button type="button" intent="secondary" loading={running(refreshStatus)} disabled={switching||running(refreshStatus)} onClick={refreshCatalog}>Refresh catalog</Button>}><UiDensity density="compact" className="bv-editor-dialog bv-download-manager-body" aria-busy={switching||running(refreshStatus)}><Callout tone="info" title={`${category.label} · ${channel==="stable"?"Stable":"Experimental"}`}>{category.notice}</Callout>{channel==="experimental"&&<Callout tone="warning" title="Experimental catalog">Experimental LUTs may change or be removed and are not yet fully validated.</Callout>}<div className="bv-download-filters"><TextField label="Search" value={query} onValue={setQuery} placeholder="Names, categories, or sources…"/><OptionSet label="Status" variant="segmented" value={statusFilter} options={[{value:"all",label:`All (${entries.length})`},{value:"available",label:`Available (${availableCount})`},{value:"installed",label:`Installed (${installedCount})`}]} onValue={value=>setStatusFilter(value as StatusFilter)}/></div>{error&&<Callout tone="danger" title="Catalog unavailable">{error}</Callout>}{refreshStatus.phase==="failed"&&<Callout tone="warning" title="Catalog update unavailable">{refreshStatus.last_error??"The last valid local catalog remains available."}</Callout>}<p className="bv-lut-download-hint">Catalog channel {channel} · version {catalogVersion}. Installed resources refresh automatically. If an already open selector stays stale, focus the graph and press R.</p>{!visible.length&&!error?<EmptyState title="No matching downloads" description="Change the status filter, channel, or search text."/>:<div className="bv-lut-download-list">{visible.map(item=>{const itemKey=catalogItemKey(channel,catalogVersion,item.id);return <article key={itemKey}><div><h3>{item.name}</h3><p>{item.description}</p><small>{item.category} · recommended {Math.round(item.recommended_strength*100)}% · {item.input_profile}</small><small>Source: <a href={item.source_url} target="_blank" rel="noreferrer">{item.source_name}</a> · <a href={item.license_url} target="_blank" rel="noreferrer">{item.license_label}</a></small>{messages[itemKey]&&<small>{messages[itemKey]}</small>}</div><Button type="button" intent={item.installed?"success":"primary"} loading={busy.has(itemKey)} disabled={item.installed||busy.has(itemKey)} onClick={()=>install(item)}>{item.installed?"Installed":"Download"}</Button></article>})}</div>}</UiDensity></BvManagedWindow>;
}
export function openDownloadManager(initialCategory:string,onInstalled?:(category:string,path:string)=>void){mountBvView(close=>createElement(DownloadManager,{close,onInstalled,initialCategory}),{key:"bv-download-manager",scope:"global"})}
export function openLutDownloadDialog(onInstalled?:(path:string)=>void){openDownloadManager("luts",onInstalled?(category,path)=>{if(category==="luts")onInstalled(path)}:undefined)}
