import React,{createElement,useEffect,useMemo,useState}from"react";
import{getApi}from"../appHelper.js";
import{Button,BvManagedWindow,Callout,CompactSelect,EmptyState,OptionSet,TextField,UiDensity,mountBvView}from"../ui";

type DownloadItem={id:string;name:string;category:string;description:string;recommended_strength:number;input_profile:string;source_name:string;source_url:string;license_label:string;license_url:string;installed?:boolean};
type DownloadCategory={id:string;label:string;load:()=>Promise<DownloadItem[]>;install:(item:DownloadItem)=>Promise<string>;notice:string};
type StatusFilter="all"|"available"|"installed";

const LUT_CATEGORY:DownloadCategory={id:"luts",label:"LUTs",notice:"Curated direct downloads. License information is advisory; verify the linked source terms for your use case.",load:async()=>{const response=await getApi().fetchApi("/bv_nodepack/luts/catalog");if(!response.ok)throw new Error(await response.text());const value=await response.json();return Array.isArray(value?.entries)?value.entries:[]},install:async item=>{const response=await getApi().fetchApi("/bv_nodepack/luts/install",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id})});if(!response.ok)throw new Error(await response.text());const value=await response.json();return String(value.installed.relative_path)}};
export const DOWNLOAD_CATEGORIES:DownloadCategory[]=[LUT_CATEGORY];

function DownloadManager({close,onInstalled,initialCategory="luts"}:{close:()=>void;onInstalled:(category:string,path:string)=>void;initialCategory?:string}){
    const[categoryId,setCategoryId]=useState(initialCategory),[entries,setEntries]=useState<DownloadItem[]>([]),[query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState<StatusFilter>("all"),[busy,setBusy]=useState<Set<string>>(new Set()),[messages,setMessages]=useState<Record<string,string>>({}),[error,setError]=useState("");
    const category=DOWNLOAD_CATEGORIES.find(item=>item.id===categoryId)??DOWNLOAD_CATEGORIES[0],refresh=()=>category.load().then(setEntries);
    useEffect(()=>{setEntries([]);setError("");refresh().catch(reason=>setError(String(reason instanceof Error?reason.message:reason)))},[categoryId]);
    const visible=useMemo(()=>{const needle=query.trim().toLowerCase();return entries.filter(item=>{const statusMatches=statusFilter==="all"||(statusFilter==="installed"?item.installed:!item.installed),queryMatches=!needle||`${item.name} ${item.category} ${item.description} ${item.source_name}`.toLowerCase().includes(needle);return statusMatches&&queryMatches})},[entries,query,statusFilter]);
    const install=async(item:DownloadItem)=>{setBusy(current=>new Set(current).add(item.id));setMessages(current=>({...current,[item.id]:"Downloading…"}));try{const path=await category.install(item);setMessages(current=>({...current,[item.id]:"Installed"}));onInstalled(category.id,path);await refresh()}catch(reason){setMessages(current=>({...current,[item.id]:String(reason instanceof Error?reason.message:reason)}))}finally{setBusy(current=>{const next=new Set(current);next.delete(item.id);return next})}};
    const context=<CompactSelect className="bv-download-category-select" label="Download category" value={category.id} options={DOWNLOAD_CATEGORIES.map(item=>({value:item.id,label:item.label}))} onValue={setCategoryId}/>;
    const availableCount=entries.filter(item=>!item.installed).length,installedCount=entries.length-availableCount;
    return <BvManagedWindow open title="BV Download Manager" shortTitle="Downloads" context={context} initialGeometry={{width:1040,height:720}} minSize={{width:420,height:360}} onClose={close} status={`${busy.size} active download${busy.size===1?"":"s"}`}><UiDensity density="compact" className="bv-editor-dialog bv-download-manager-body"><Callout tone="info" title={category.label}>{category.notice}</Callout><div className="bv-download-filters"><TextField label="Search" value={query} onValue={setQuery} placeholder="Names, categories, or sources…"/><OptionSet label="Status" variant="segmented" value={statusFilter} options={[{value:"all",label:`All (${entries.length})`},{value:"available",label:`Available (${availableCount})`},{value:"installed",label:`Installed (${installedCount})`}]} onValue={value=>setStatusFilter(value as StatusFilter)}/></div>{error&&<Callout tone="danger" title="Catalog unavailable">{error}</Callout>}<p className="bv-lut-download-hint">Installed resources refresh automatically. If an already open selector stays stale, focus the graph and press R.</p>{!visible.length&&!error?<EmptyState title="No matching downloads" description="Change the status filter or search text."/>:<div className="bv-lut-download-list">{visible.map(item=><article key={item.id}><div><h3>{item.name}</h3><p>{item.description}</p><small>{item.category} · recommended {Math.round(item.recommended_strength*100)}% · {item.input_profile}</small><small>Source: <a href={item.source_url} target="_blank" rel="noreferrer">{item.source_name}</a> · <a href={item.license_url} target="_blank" rel="noreferrer">{item.license_label}</a></small>{messages[item.id]&&<small>{messages[item.id]}</small>}</div><Button type="button" intent={item.installed?"success":"primary"} loading={busy.has(item.id)} disabled={item.installed||busy.has(item.id)} onClick={()=>install(item)}>{item.installed?"Installed":"Download"}</Button></article>)}</div>}</UiDensity></BvManagedWindow>;
}
export function openDownloadManager(initialCategory:string,onInstalled:(category:string,path:string)=>void){mountBvView(close=>createElement(DownloadManager,{close,onInstalled,initialCategory}),{key:"bv-download-manager"})}
export function openLutDownloadDialog(onInstalled:(path:string)=>void){openDownloadManager("luts",(category,path)=>{if(category==="luts")onInstalled(path)})}
