import { NumberField, ResourcePicker, ToggleField, type ResourcePickerCollector } from "../ui/components";
import { commitLutSourceConfig } from "./lutV3Catalog";
import { scheduleDetailerPromptV3Reconcile } from "./detailerV3Graph";

export type LutEasyJob={id:string;scope:"global"|"regional";region_ids:string[];mask_composition:"union";lut_source:{collector_id:string;resource_id:string};strength:number;mask_invert:boolean;detector_source:{collector_id:string;resource_id:string}|null};
export type LutEasyConfig={version:1;jobs:LutEasyJob[]};
const widget=(node:any)=>node?.widgets?.find((item:any)=>item.name==="lut_v3_config_json");
export const emptyLutEasyConfig=():LutEasyConfig=>({version:1,jobs:[]});
export function readLutEasyConfig(node:any):LutEasyConfig{try{const value=JSON.parse(String(widget(node)?.value??"{}"));if(value?.version!==1||!Array.isArray(value.jobs))return emptyLutEasyConfig();return{version:1,jobs:value.jobs.map((job:any)=>({...job,scope:job.scope==="global"?"global":"regional"}))};}catch{return emptyLutEasyConfig();}}
export function writeLutEasyConfig(node:any,config:LutEasyConfig){commitLutSourceConfig(node,JSON.stringify(config));scheduleDetailerPromptV3Reconcile(node);window.dispatchEvent(new CustomEvent("bv-regional-lut-config-changed",{detail:{node}}));return config;}
function LutEasyPicker({node,config,regionId,collectors,detectorCollectors,onConfig}:{node:any;config:LutEasyConfig;regionId:string|null;collectors:ResourcePickerCollector[];detectorCollectors:ResourcePickerCollector[];onConfig:(value:LutEasyConfig)=>void}){const scope=regionId?"regional":"global",matches=(item:LutEasyJob)=>item.scope===scope&&(scope==="global"||item.region_ids.length===1&&item.region_ids[0]===regionId),job=config.jobs.find(matches),update=(next:LutEasyConfig)=>onConfig(writeLutEasyConfig(node,next));return <div className="bv-lora-v3-scope-picker"><ResourcePicker label={scope==="global"?"Global LUT":"Regional LUT"} emptyLabel="No LUT" collectors={collectors} collectorId={job?.lut_source.collector_id??""} resourceId={job?.lut_source.resource_id??""} onSelection={(collector_id,resource_id)=>{const rest=config.jobs.filter(item=>!matches(item));update({version:1,jobs:collector_id&&resource_id?[...rest,{id:job?.id??crypto.randomUUID(),scope,region_ids:regionId?[regionId]:[],mask_composition:"union",lut_source:{collector_id,resource_id},strength:job?.strength??1,mask_invert:job?.mask_invert??false,detector_source:job?.detector_source??null}]:rest});}}/>{job&&<><ResourcePicker label="Detector mask" emptyLabel={scope==="global"?"No detector · entire image":"No detector · use region mask"} collectors={detectorCollectors} collectorId={job.detector_source?.collector_id??""} resourceId={job.detector_source?.resource_id??""} onSelection={(collector_id,resource_id)=>update({...config,jobs:config.jobs.map(item=>item.id===job.id?{...item,detector_source:collector_id&&resource_id?{collector_id,resource_id}:null}:item)})}/><NumberField label="LUT strength" value={job.strength} min={0} max={1} step={.05} onValue={strength=>update({...config,jobs:config.jobs.map(item=>item.id===job.id?{...item,strength}:item)})}/><ToggleField label="Mask" value={job.mask_invert} trueLabel="Inverted · grade outside" falseLabel="Normal · grade inside" onValue={mask_invert=>update({...config,jobs:config.jobs.map(item=>item.id===job.id?{...item,mask_invert}:item)})}/></>}</div>}
export function LutEasyRegionPicker(props:{node:any;config:LutEasyConfig;regionId:string;collectors:ResourcePickerCollector[];detectorCollectors:ResourcePickerCollector[];onConfig:(value:LutEasyConfig)=>void}){return <LutEasyPicker {...props}/>}
export function LutEasyGlobalPicker(props:{node:any;config:LutEasyConfig;collectors:ResourcePickerCollector[];detectorCollectors:ResourcePickerCollector[];onConfig:(value:LutEasyConfig)=>void}){return <LutEasyPicker {...props} regionId={null}/>}
