import React, { useEffect, useState } from "react";
import { Bounds } from "./geometry";
import { GeometryLayer, PromptPair, Region } from "./model";
import PromptTextarea from "../completion/PromptTextarea";
import { NamedLoraStack, RegionalLoraBindings } from "./loraBindings";
import { BvNumberField, BvSelect } from "../ui/controls";
import { Accordion, Button, ColorField, FieldFrame, UiDensity } from "../ui/components";

type Props = {
    mode?: "selection" | "region" | "document"; region: Region | null; layer: GeometryLayer | null; bounds: Bounds | null;
    canvas: { width: number; height: number }; globalPrompts: PromptPair; backgroundPrompts: PromptPair; negativeMode: "auto" | "prompt" | "zero_out";
    onNegativeMode: (value: Props["negativeMode"]) => void; onGlobalPrompts: (value: PromptPair) => void; onBackgroundPrompts: (value: PromptPair) => void;
    onRegion: (fn: (region: Region) => void) => void; automaticRegionColor: string | null; onLayerBounds: (bounds: Bounds) => void;
    onBrushSetting: (field: "size" | "hardness" | "opacity" | "shape" | "pressure_mode", value: number | string) => void;
    promptSections: { region: boolean; global: boolean; background: boolean }; onPromptSection: (section: keyof Props["promptSections"], open: boolean) => void;
    loraBindings: RegionalLoraBindings; loraStacks: NamedLoraStack[]; onGlobalLoraStack: (stackId: string | null) => void; onRegionLoraStack: (regionId: string, stackId: string | null) => void;
};

const StackOptions = ({ stacks }: { stacks: NamedLoraStack[] }) => <><option value="">None</option>{stacks.map(stack => <option key={stack.id} value={stack.id}>{stack.name}</option>)}</>;
const PromptEditor = ({ title, scope, value, open, onOpen, onChange }: { title: string; scope: "global" | "background" | "region"; value: PromptPair; open: boolean; onOpen: (open: boolean) => void; onChange: (value: PromptPair) => void }) => <Accordion value={open?[scope]:[]} onValue={ids=>onOpen(ids.includes(scope))} items={[{id:scope,title,content:<div className="bv-prompt-editor-fields"><FieldFrame label="Positive"><PromptTextarea value={value.positive_source} onValue={positive_source => onChange({ ...value, positive_source })} completionContext={{ scope, polarity: "positive" }}/></FieldFrame><FieldFrame label="Negative"><PromptTextarea value={value.negative_source} onValue={negative_source => onChange({ ...value, negative_source })} completionContext={{ scope, polarity: "negative" }}/></FieldFrame></div>} ]}/>;
const RegionMaskAppearance = ({ region, automaticColor, onRegion }: { region: Region; automaticColor: string | null; onRegion: Props["onRegion"] }) => <section className="bv-inspector-section"><h3>Mask &amp; appearance</h3><BvNumberField label="Feather" value={region.mask.feather} min={0} max={.5} step={.005} onChange={value => onRegion(current => { current.mask.feather = value; })}/><div className="region-color-control"><ColorField label="Display color" help="Editor display only. It does not change masks or sampling." value={region.authoring.color} onValue={value => onRegion(current => { current.authoring.color = value.toUpperCase(); })}/><Button density="compact" disabled={!automaticColor || region.authoring.color.toUpperCase() === automaticColor} onClick={() => onRegion(current => { if (automaticColor) current.authoring.color = automaticColor; })}>Reset to Automatic</Button></div></section>;

export default function OptionsPanel(props: Props) {
    const brush = props.layer?.geometries.find(geometry => geometry.type === "brush_stroke");
    const [activeTab, setActiveTab] = useState<"selection" | "region" | "document">(props.mode ?? (props.layer ? "selection" : props.region ? "region" : "document"));
    useEffect(() => setActiveTab(props.mode ?? (props.layer ? "selection" : props.region ? "region" : "document")), [props.layer?.id, props.mode, props.region?.id]);
    return <UiDensity density="compact" className="inspector-density"><aside className={`inspector bv-ui ${props.mode ? "fixed-inspector" : ""}`}>
        <nav className="inspector-tabs" role="tablist" aria-label="Inspector context"><Button intent="ghost" role="tab" aria-selected={activeTab === "selection"} disabled={!props.layer} onClick={() => setActiveTab("selection")}>Selection</Button><Button intent="ghost" role="tab" aria-selected={activeTab === "region"} disabled={!props.region} onClick={() => setActiveTab("region")}>Region</Button><Button intent="ghost" role="tab" aria-selected={activeTab === "document"} onClick={() => setActiveTab("document")}>Document</Button></nav>
        <div className="inspector-tab-panel" role="tabpanel" hidden={activeTab !== "selection"}>{props.region && <RegionMaskAppearance region={props.region} automaticColor={props.automaticRegionColor} onRegion={props.onRegion}/>}{props.layer && props.bounds ? <section className="bv-inspector-section"><h3>Layer</h3><div className="bv-layer-bounds-grid">{(["x", "y", "width", "height"] as const).map(key => <BvNumberField key={key} label={key.toUpperCase()} value={+props.bounds![key].toFixed(4)} min={0} max={1} step={.001} slider={false} onChange={value => props.onLayerBounds({ ...props.bounds!, [key]: value })}/>)}</div>{brush && <><BvNumberField label="Stroke width" value={brush.size} min={.001} max={1} step={.005} onChange={value => props.onBrushSetting("size", value)} unit="×"/><div className="bv-compact-grid"><BvNumberField label="Hardness" value={brush.hardness} min={0} max={1} step={.05} onChange={value => props.onBrushSetting("hardness", value)}/><BvNumberField label="Opacity" value={brush.opacity} min={0} max={1} step={.05} onChange={value => props.onBrushSetting("opacity", value)}/></div><div className="bv-compact-grid"><BvSelect label="Shape" value={brush.shape ?? "round"} onChange={value => props.onBrushSetting("shape", value)}><option value="round">Round</option><option value="square">Square</option></BvSelect><BvSelect label="Pressure" value={brush.pressure_mode ?? "constant"} onChange={value => props.onBrushSetting("pressure_mode", value)}><option value="constant">Constant</option><option value="stylus">Stylus</option></BvSelect></div></>}</section> : <p className="option-hint">Select a layer to edit its geometry.</p>}</div>
        <div className="inspector-tab-panel" role="tabpanel" hidden={activeTab !== "region"}>{props.region && <section className="bv-inspector-section"><h3>Region</h3><BvSelect label="Usage" help="Controls whether this region participates in the main render, Detailer output, or both." value={props.region.usage} onChange={value => props.onRegion(region => { region.usage = value as Region["usage"]; })}><option value="generation">Generation</option><option value="detailer">Detailer only</option><option value="both">Generation + Detailer</option></BvSelect><BvSelect label="Additional LoRA Stack" help="Added to the global stack. Source activation and strengths remain unchanged." value={props.loraBindings.regions[props.region.id] ?? ""} onChange={value => props.onRegionLoraStack(props.region!.id, value || null)}><StackOptions stacks={props.loraStacks}/></BvSelect><BvNumberField label="Strength" value={props.region.strength} min={0} max={10} step={.05} onChange={value => props.onRegion(region => { region.strength = value; })}/><PromptEditor title="Region Prompt" scope="region" value={props.region.prompts} open={props.promptSections.region} onOpen={open => props.onPromptSection("region", open)} onChange={value => props.onRegion(region => { region.prompts = value; })}/></section>}</div>
        <div className="inspector-tab-panel" role="tabpanel" hidden={activeTab !== "document"}><section className="bv-inspector-section"><h3>Document Prompts</h3><BvSelect label="Global LoRA Stack" help="Applied globally and inherited by every region." value={props.loraBindings.global_stack_id ?? ""} onChange={value => props.onGlobalLoraStack(value || null)}><StackOptions stacks={props.loraStacks}/></BvSelect><BvSelect label="Negative Mode" value={props.negativeMode} onChange={value => props.onNegativeMode(value as Props["negativeMode"])}><option value="auto">Auto</option><option value="prompt">Prompt</option><option value="zero_out">Zero out</option></BvSelect><PromptEditor title="Global" scope="global" value={props.globalPrompts} open={props.promptSections.global} onOpen={open => props.onPromptSection("global", open)} onChange={props.onGlobalPrompts}/><PromptEditor title="Background" scope="background" value={props.backgroundPrompts} open={props.promptSections.background} onOpen={open => props.onPromptSection("background", open)} onChange={props.onBackgroundPrompts}/></section></div>
    </aside></UiDensity>;
}
