import React, { type ReactNode, useEffect, useState } from "react";
import { Bounds } from "./geometry";
import { GeometryLayer, PromptPair, Region } from "./model";
import { PromptPairFields, ReferenceSearchToggle } from "../completion/referenceFields";
import type { ReferenceChoice } from "../completion/referenceMentions";
import { NamedLoraStack, RegionalLoraBindings } from "./loraBindings";
import { BvNumberField, BvSelect } from "../ui/controls";
import { Accordion, Button, ColorField, FieldFrame, UiDensity, SegmentedToggleGroup, ToolTabs } from "../ui/components";

type Props = {
    mode?: "selection" | "region" | "document"; region: Region | null; layer: GeometryLayer | null; bounds: Bounds | null;
    canvas: { width: number; height: number }; globalPrompts: PromptPair; backgroundPrompts: PromptPair; negativeMode: "auto" | "prompt" | "zero_out";
    onNegativeMode: (value: Props["negativeMode"]) => void; onGlobalPrompts: (value: PromptPair) => void; onBackgroundPrompts: (value: PromptPair) => void;
    onRegion: (fn: (region: Region) => void) => void; automaticRegionColor: string | null; onLayerBounds: (bounds: Bounds) => void;
    onBrushSetting: (field: "size" | "hardness" | "opacity" | "shape" | "pressure_mode", value: number | string) => void;
    promptSections: { region: boolean; global: boolean; background: boolean }; onPromptSection: (section: keyof Props["promptSections"], open: boolean) => void;
    loraBindings: RegionalLoraBindings; loraStacks: NamedLoraStack[]; onGlobalLoraStack: (stackId: string | null) => void; onRegionLoraStack: (regionId: string, stackId: string | null) => void;
    referenceChoices: ReferenceChoice[];
    globalTools: string[]; regionTools: string[]; onGlobalTools: (ids: string[]) => void; onRegionTools: (ids: string[]) => void;
    loraV3GlobalEditor?:ReactNode; loraV3RegionEditor?:ReactNode; referenceEditor?:ReactNode;
    detailerEasyRegionEditor?:ReactNode; lutEasyRegionEditor?:ReactNode; lutEasyGlobalEditor?:ReactNode;
};

const StackOptions = ({ stacks }: { stacks: NamedLoraStack[] }) => <><option value="">None</option>{stacks.map(stack => <option key={stack.id} value={stack.id}>{stack.name}</option>)}</>;
const PromptEditor = ({ title, scope, value, open, onOpen, onChange, choices }: { title: string; scope: "global" | "background" | "region"; value: PromptPair; open: boolean; onOpen: (open: boolean) => void; onChange: (value: PromptPair) => void; choices:ReferenceChoice[] }) => <Accordion value={open?[scope]:[]} onValue={ids=>onOpen(ids.includes(scope))} items={[{id:scope,title,actions:<ReferenceSearchToggle value={value.reference_editor===true} onValue={reference_editor=>onChange({...value,reference_editor})}/>,content:<PromptPairFields value={value} onValue={onChange} scope={scope} choices={choices}/>} ]}/>;
const RegionMaskAppearance = ({ region, automaticColor, onRegion }: { region: Region; automaticColor: string | null; onRegion: Props["onRegion"] }) => <section className="bv-inspector-section"><h3>Mask &amp; appearance</h3><BvNumberField label="Feather" value={region.mask.feather} min={0} max={.5} step={.005} onChange={value => onRegion(current => { current.mask.feather = value; })}/><div className="region-color-control"><div className="region-color-split"><ColorField label="Display color" help="Editor display only. It does not change masks or sampling." value={region.authoring.color} onValue={value => onRegion(current => { current.authoring.color = value.toUpperCase(); })}/><Button density="compact" intent="ghost" iconOnly aria-label="Reset display color to automatic" title="Reset to automatic" disabled={!automaticColor || region.authoring.color.toUpperCase() === automaticColor} onClick={() => onRegion(current => { if (automaticColor) current.authoring.color = automaticColor; })}>↶</Button></div></div></section>;

export default function OptionsPanel(props: Props) {
    const brush = props.layer?.geometries.find(geometry => geometry.type === "brush_stroke");
    const [activeTab, setActiveTab] = useState<"selection" | "region" | "document">(props.mode ?? (props.layer ? "selection" : props.region ? "region" : "document"));
    useEffect(() => setActiveTab(props.mode ?? (props.layer ? "selection" : props.region ? "region" : "document")), [props.layer?.id, props.mode, props.region?.id]);
    return <UiDensity density="compact" className="inspector-density"><aside className={`inspector bv-ui ${props.mode ? "fixed-inspector" : ""}`}>
        <nav className="inspector-tabs" role="tablist" aria-label="Inspector context"><Button intent="ghost" role="tab" aria-selected={activeTab === "selection"} disabled={!props.layer} onClick={() => setActiveTab("selection")}>Selection</Button><Button intent="ghost" role="tab" aria-selected={activeTab === "region"} disabled={!props.region} onClick={() => setActiveTab("region")}>Region</Button><Button intent="ghost" role="tab" aria-selected={activeTab === "document"} onClick={() => setActiveTab("document")}>Document</Button></nav>
        <div className="inspector-tab-panel" role="tabpanel" hidden={activeTab !== "selection"}>{props.region && <RegionMaskAppearance region={props.region} automaticColor={props.automaticRegionColor} onRegion={props.onRegion}/>}{props.layer && props.bounds ? <section className="bv-inspector-section"><h3>Layer</h3><div className="bv-layer-bounds-grid">{(["x", "y", "width", "height"] as const).map(key => { const axisSize=key==="x"||key==="width"?props.canvas.width:props.canvas.height; return <BvNumberField key={key} label={key.toUpperCase()} value={Math.round(props.bounds![key]*axisSize)} min={0} max={axisSize} step={1} unit="px" onChange={value => props.onLayerBounds({ ...props.bounds!, [key]: value/axisSize })}/>; })}</div>{brush && <><BvNumberField label="Stroke width" value={brush.size} min={.001} max={1} step={.005} onChange={value => props.onBrushSetting("size", value)} unit="×"/><div className="bv-compact-grid"><BvNumberField label="Hardness" value={brush.hardness} min={0} max={1} step={.05} onChange={value => props.onBrushSetting("hardness", value)}/><BvNumberField label="Opacity" value={brush.opacity} min={0} max={1} step={.05} onChange={value => props.onBrushSetting("opacity", value)}/></div><div className="bv-compact-grid"><BvSelect label="Shape" value={brush.shape ?? "round"} onChange={value => props.onBrushSetting("shape", value)}><option value="round">Round</option><option value="square">Square</option></BvSelect><BvSelect label="Pressure" value={brush.pressure_mode ?? "constant"} onChange={value => props.onBrushSetting("pressure_mode", value)}><option value="constant">Constant</option><option value="stylus">Stylus</option></BvSelect></div></>}</section> : <p className="option-hint">Select a layer to edit its geometry.</p>}</div>
        <div className="inspector-tab-panel" role="tabpanel" hidden={activeTab !== "region"}>{props.region && <section className="bv-inspector-section"><h3 className="bv-context-heading" title={`Region: ${props.region.name}`}>Region: {props.region.name}</h3><FieldFrame as="div" label="Usage"><SegmentedToggleGroup label="Region usage" required items={[{id:"generation",label:"Generation"},{id:"detailer",label:"Detailer"}]} value={props.region.usage==="both"?["generation","detailer"]:[props.region.usage]} onValue={ids=>props.onRegion(region=>{region.usage=ids.length===2?"both":ids[0] as Region["usage"];})}/></FieldFrame>{props.detailerEasyRegionEditor}<ToolTabs label="Region tools" value={props.regionTools} onValue={props.onRegionTools} items={[{id:"lora",label:"LoRA",content:props.loraV3RegionEditor??<BvSelect label="Additional LoRA Stack" value={props.loraBindings.regions[props.region.id]??""} onChange={value=>props.onRegionLoraStack(props.region!.id,value||null)}><StackOptions stacks={props.loraStacks}/></BvSelect>},{id:"lut",label:"LUT",content:props.lutEasyRegionEditor}]}/><BvNumberField label="Strength" value={props.region.strength} min={0} max={10} step={.05} onChange={value => props.onRegion(region => { region.strength = value; })}/><PromptEditor key={props.region.id} choices={props.referenceChoices} title="Region Prompt" scope="region" value={props.region.prompts} open={props.promptSections.region} onOpen={open => props.onPromptSection("region", open)} onChange={value => props.onRegion(region => { region.prompts = value; })}/></section>}</div>
        <div className="inspector-tab-panel" role="tabpanel" hidden={activeTab !== "document"}><section className="bv-inspector-section"><ToolTabs label="Global tools" value={props.globalTools} onValue={props.onGlobalTools} items={[{id:"lora",label:"LoRA",content:props.loraV3GlobalEditor??<BvSelect label="Global LoRA Stack" value={props.loraBindings.global_stack_id??""} onChange={value=>props.onGlobalLoraStack(value||null)}><StackOptions stacks={props.loraStacks}/></BvSelect>},{id:"lut",label:"LUT",content:props.lutEasyGlobalEditor},{id:"references",label:"References",content:props.referenceEditor}]}/><BvSelect label="Negative Mode" value={props.negativeMode} onChange={value => props.onNegativeMode(value as Props["negativeMode"])}><option value="auto">Auto</option><option value="prompt">Prompt</option><option value="zero_out">Zero out</option></BvSelect><PromptEditor choices={props.referenceChoices} title="Global" scope="global" value={props.globalPrompts} open={props.promptSections.global} onOpen={open => props.onPromptSection("global", open)} onChange={props.onGlobalPrompts}/><PromptEditor choices={props.referenceChoices} title="Background (Outside Regions)" scope="background" value={props.backgroundPrompts} open={props.promptSections.background} onOpen={open => props.onPromptSection("background", open)} onChange={props.onBackgroundPrompts}/></section></div>
    </aside></UiDensity>;
}
