import{legacyDebugVisible}from"./legacyPorts.js";
import{markM0NodeElement}from"./m0VisualProjection.js";

const PROVIDERS=new Set(["BV_RUNTIME_RESOURCE_PROVIDER","BV_RUNTIME_RESOURCE_PROVIDER_M0"]);
const LAYOUT_VERSION=1;
let userResizeProbe=(node:any)=>false;
const internal=(slot:any)=>PROVIDERS.has(String(slot?.type??""))||slot?.__bvM0ResourceSlot===true||slot?.__bvResourceSlot===true;
const visibleLegacy=(slot:any)=>slot?.__bvLegacyPort===true&&!slot.hidden;
const measurementView=(node:any,overrides:Record<PropertyKey,unknown>)=>{const local=new Map<PropertyKey,unknown>(Reflect.ownKeys(overrides).map(key=>[key,overrides[key]]));return new Proxy(node,{get(target,key){return local.has(key)?local.get(key):Reflect.get(target,key,target)},set(_target,key,value){local.set(key,value);return true}})};

export function setProjectedSlotLabel(slot:any,label:string){if(!slot)return;slot.label=label;slot.localized_name=label;}

export function configureProjectedPortLayout(options:{isUserResizing?:(node:any)=>boolean}){userResizeProbe=options.isUserResizing??(()=>false)}

export function markProjectedProvider(slot:any){if(!slot)return;slot.hidden=true;slot.label="";slot.localized_name="";slot.__bvResourceSlot=true;slot.__bvM0ResourceSlot=true;slot.__bvM0PortHidden=true;}

export function suppressInitialProjectedProviderDefinitions(nodeData:any){const optional=nodeData?.input?.optional;if(!optional)return[];const removed:string[]=[];for(const [name,spec]of Object.entries(optional)){if(PROVIDERS.has(String((spec as any)?.[0]??""))){delete optional[name];removed.push(name)}}return removed}

export function installRegionalPromptCreationLayout(nodeType:any){const prototype=nodeType?.prototype,original=prototype?.computeSize;if(!prototype||typeof original!=="function"||prototype.__bvRegionalPromptCreationLayout)return;prototype.__bvRegionalPromptCreationLayout=true;prototype.computeSize=function(){if(this.__bvRegionalPromptUiReady)return original.apply(this,arguments);const view=measurementView(this,{inputs:(this.inputs??[]).filter((slot:any)=>!internal(slot)),outputs:(this.outputs??[]).filter((slot:any)=>slot?.name!=="lora_bindings"),widgets:[{type:"button",name:"open_regional_editor",computeSize:()=>[0,20]},{type:"button",name:"quick_edit_regional_prompts",computeSize:()=>[0,20]}]});return original.apply(view,arguments)}}

export function retainNeededProjectedInputs(node:any,wantedNames:string[],matches:(slot:any)=>boolean){const wanted=new Set(wantedNames);for(const {slot,index} of (node.inputs??[]).map((slot:any,index:number)=>({slot,index})).filter(({slot}:any)=>matches(slot)&&!wanted.has(String(slot.name))&&slot.link==null).sort((a:any,b:any)=>b.index-a.index))node.removeInput?.(index);for(const name of wantedNames){const slot=node.inputs?.find((item:any)=>item.name===name);if(slot)markProjectedProvider(slot);}}

function projected(slots:any[]|undefined,debug:boolean){const result:any[]=[],provider=debug?(slots??[]).find(internal):undefined;for(const slot of slots??[]){if(internal(slot)){if(slot===provider)result.push(slot);continue}if(slot?.__bvLegacyPort){if(visibleLegacy(slot))result.push(slot);continue}if(!slot?.hidden)result.push(slot)}return result}

export function installProjectedPortLayout(node:any){if(!node||node.__bvProjectedPortOriginalComputeSize||typeof node.computeSize!=="function")return;const original=node.computeSize,resize=node.onResize;node.properties??={};if(node.properties.bvProjectedLayoutVersion!==LAYOUT_VERSION){delete node.properties.bvProjectedUserHeight;node.properties.bvProjectedLayoutVersion=LAYOUT_VERSION}node.__bvProjectedPortOriginalComputeSize=original;node.computeSize=function(){const inputs=this.inputs??[],outputs=this.outputs??[],nextInputs=projected(inputs,legacyDebugVisible()),nextOutputs=projected(outputs,legacyDebugVisible()),measure=(measuredInputs:any[],measuredOutputs:any[])=>original.apply(measurementView(this,{size:[Number(this.size?.[0]??0),60],inputs:measuredInputs,outputs:measuredOutputs}),arguments);const full=measure(inputs,outputs),compact=measure(nextInputs,nextOutputs),removedRows=Math.max(inputs.length,outputs.length)-Math.max(nextInputs.length,nextOutputs.length),structuralHeight=Math.max(60,Number(full?.[1]??0)-Math.max(0,removedRows)*20);return[Math.max(Number(compact?.[0]??0),Number(full?.[0]??0)),Math.min(Number(compact?.[1]??structuralHeight),structuralHeight)]};node.onResize=function(){const result=resize?.apply(this,arguments);if(!this.__bvProjectedPortInternalResize&&userResizeProbe(this)){this.properties??={};this.properties.bvProjectedLayoutVersion=LAYOUT_VERSION;this.properties.bvProjectedUserHeight=Math.max(0,Number(this.size?.[1]??0))}return result};node.__bvRefreshPortProjection=()=>scheduleProjectedPortLayout(node)}

export function compactProjectedPortLayout(node:any,minWidth=220,minHeight=60){installProjectedPortLayout(node);if(!node?.setSize)return;const width=Math.max(Number(node.size?.[0]??0),minWidth),userHeight=Math.max(0,Number(node.properties?.bvProjectedUserHeight??0)),computed=node.computeSize?.()??node.size??[minWidth,minHeight],arrangementPadding=Math.max(0,Number(node.__bvProjectedArrangementPadding??0)),measuredHeight=Math.max(minHeight,Number(computed[1]??minHeight)+arrangementPadding),next:[number,number]=[Math.max(width,Number(computed[0]??0),minWidth),Math.max(measuredHeight,userHeight)];node.__bvProjectedPortInternalResize=true;try{if(Number(node.size?.[0]??0)!==next[0]||Number(node.size?.[1]??0)!==next[1])node.setSize(next)}finally{node.__bvProjectedPortInternalResize=false}node.__bvM0ResourceConsumer=(node.inputs??[]).some(internal);const first=(node.inputs??[]).findIndex(internal);node.__bvM0FanInAnchorSlot=first>=0?first:undefined;if(typeof document!=="undefined")markM0NodeElement(node,"consumer",legacyDebugVisible());node.setDirtyCanvas?.(true,true);node.graph?.setDirtyCanvas?.(true,true)}

export function scheduleProjectedPortLayout(node:any){if(!node||node.__bvProjectedPortLayoutScheduled)return;node.__bvProjectedPortLayoutScheduled=true;let deferred=false;for(const delay of[0,50,150])setTimeout(()=>{if(userResizeProbe(node))deferred=true;else{deferred=false;compactProjectedPortLayout(node)}if(delay===150){node.__bvProjectedPortLayoutScheduled=false;if(deferred)scheduleProjectedPortLayout(node)}},delay)}
